import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main () {
  const hashedPassword = await bcrypt.hash('user123', 10) // ?hash de contrasena generica
  // ?json de usuarios de prueba
  const usuarios = [
    {
      document_type: 2,
      document: '987654321',
      name: 'Daniel Salazar.',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '123 Calle Falsa',
      phone: '3201234567',
      email: 'jdps1006@gmail.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/57/3a/46/573a46c7818f8cca76e394ac5af72542.jpg',
      id_rol: 1
    },
    {
      document_type: 2,
      document: '123456789',
      name: 'Laura Pérez',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '456 Avenida Siempre Viva',
      phone: '3212345678',
      email: 'lauraperez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654322',
      name: 'Juan Gómez',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '789 Calle Luna',
      phone: '3208765432',
      email: 'juangomez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456780',
      name: 'Ana Martínez',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '101 Calle Sol',
      phone: '3218765432',
      email: 'anamartinez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654323',
      name: 'Ricardo López',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '202 Calle Estrella',
      phone: '3207654321',
      email: 'ricardolopez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456781',
      name: 'Marta Sánchez',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '303 Calle Marte',
      phone: '3217654321',
      email: 'martasanchez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654324',
      name: 'Daniel Ruiz',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '404 Calle Júpiter',
      phone: '3206543210',
      email: 'danielruiz@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456782',
      name: 'Lucía Ramírez',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '505 Calle Venus',
      phone: '3216543210',
      email: 'luciaramirez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654325',
      name: 'Jorge Torres',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '606 Calle Saturno',
      phone: '3205432109',
      email: 'jorgetorres@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456783',
      name: 'María Ortiz',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '707 Calle Urano',
      phone: '3215432109',
      email: 'mariaortiz@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654326',
      name: 'Roberto Vargas',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '808 Calle Neptuno',
      phone: '3204321098',
      email: 'robertovargas@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456784',
      name: 'Patricia Morales',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '909 Calle Plutón',
      phone: '3214321098',
      email: 'patriciamorales@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654327',
      name: 'Fernando Gil',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1010 Calle Cometa',
      phone: '3203210987',
      email: 'fernandogil@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456785',
      name: 'Sofía Castro',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1111 Calle Asteroide',
      phone: '3213210987',
      email: 'sofiacastro@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654328',
      name: 'Alejandro Díaz',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1212 Calle Estrella Fugaz',
      phone: '3202109876',
      email: 'alejandrodiaz@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456786',
      name: 'Isabel Fernández',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1313 Calle Eclipse',
      phone: '3212109876',
      email: 'isabelfernandez@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654329',
      name: 'Luis García',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1414 Calle Meteorito',
      phone: '3201098765',
      email: 'luisgarcia@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456787',
      name: 'Gabriela Molina',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1515 Calle Nebulosa',
      phone: '3211098765',
      email: 'gabrielamolina@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '987654330',
      name: 'Héctor Parra',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1616 Calle Supernova',
      phone: '3200987654',
      email: 'hectorparra@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    },
    {
      document_type: 2,
      document: '123456788',
      name: 'Paula Reyes',
      id_country: 1,
      id_department: 5,
      id_city: 330,
      address: '1717 Calle Vía Láctea',
      phone: '3210987654',
      email: 'paulareyes@example.com',
      password: hashedPassword,
      avatar: 'https://i.pinimg.com/564x/fa/59/a1/fa59a1abd2edcb8026726986fd352989.jpg',
      id_rol: 2
    }
  ]

  const tiposDeDocumentos = [
    { id_document_type: 1, name: 'CC', description: 'Cédula de Ciudadanía' },
    { id_document_type: 2, name: 'CE', description: 'Cédula de Extranjería' },
    { id_document_type: 3, name: 'NIT', description: 'Registro de Identificación Tributaria' },
    { id_document_type: 4, name: 'PP', description: 'Pasaporte' },
    { id_document_type: 5, name: 'RUT', description: 'Registro Único Tributario' }
  ]

  const Paises = [
    { id_country: 1, name: 'COLOMBIA', currency: 'COP', locale: 'es-CO' },
    { id_country: 2, name: 'VENEZUELA', currency: 'VES', locale: 'es-VE' },
    { id_country: 3, name: 'PERÚ', currency: 'PEN', locale: 'es-PE' },
    { id_country: 4, name: 'ARGENTINA', currency: 'ARS', locale: 'es-AR' },
    { id_country: 5, name: 'ECUADOR', currency: 'USD', locale: 'es-EC' },
    { id_country: 6, name: 'CHILE', currency: 'CLP', locale: 'es-CL' },
    { id_country: 7, name: 'URUGUAY', currency: 'UYU', locale: 'es-UY' },
    { id_country: 8, name: 'BOLIVIA', currency: 'BOB', locale: 'es-BO' },
    { id_country: 9, name: 'PARAGUAY', currency: 'PYG', locale: 'es-PY' },
    { id_country: 10, name: 'BRASIL', currency: 'BRL', locale: 'pt-BR' },
    { id_country: 11, name: 'MÉXICO', currency: 'MXN', locale: 'es-MX' },
    { id_country: 12, name: 'GUATEMALA', currency: 'GTQ', locale: 'es-GT' },
    { id_country: 13, name: 'EL SALVADOR', currency: 'USD', locale: 'es-SV' },
    { id_country: 14, name: 'HONDURAS', currency: 'HNL', locale: 'es-HN' },
    { id_country: 15, name: 'NICARAGUA', currency: 'NIO', locale: 'es-NI' },
    { id_country: 16, name: 'COSTA RICA', currency: 'CRC', locale: 'es-CR' },
    { id_country: 17, name: 'PANAMÁ', currency: 'USD', locale: 'es-PA' },
    { id_country: 18, name: 'CUBA', currency: 'CUP', locale: 'es-CU' },
    { id_country: 19, name: 'REPÚBLICA DOMINICANA', currency: 'DOP', locale: 'es-DO' },
    { id_country: 20, name: 'PUERTO RICO', currency: 'USD', locale: 'es-PR' },
    { id_country: 21, name: 'CANADÁ', currency: 'CAD', locale: 'en-CA' },
    { id_country: 22, name: 'ESTADOS UNIDOS', currency: 'USD', locale: 'en-US' },
    { id_country: 23, name: 'HAITÍ', currency: 'HTG', locale: 'fr-HT' },
    { id_country: 24, name: 'JAMAICA', currency: 'JMD', locale: 'en-JM' },
    { id_country: 25, name: 'TRINIDAD Y TOBAGO', currency: 'TTD', locale: 'en-TT' },
    { id_country: 26, name: 'GUYANA', currency: 'GYD', locale: 'en-GY' },
    { id_country: 27, name: 'SURINAM', currency: 'SRD', locale: 'nl-SR' },
    { id_country: 28, name: 'BELICE', currency: 'BZD', locale: 'en-BZ' },
    { id_country: 29, name: 'BARBADOS', currency: 'BBD', locale: 'en-BB' },
    { id_country: 30, name: 'SAN VICENTE Y LAS GRANADINAS', currency: 'XCD', locale: 'en-VC' },
    { id_country: 31, name: 'SANTA LUCÍA', currency: 'XCD', locale: 'en-LC' },
    { id_country: 32, name: 'ANTIGUA Y BARBUDA', currency: 'XCD', locale: 'en-AG' },
    { id_country: 33, name: 'DOMINICA', currency: 'XCD', locale: 'en-DM' },
    { id_country: 34, name: 'GRENADA', currency: 'XCD', locale: 'en-GD' },
    { id_country: 35, name: 'BAHAMAS', currency: 'BSD', locale: 'en-BS' }
  ]

  const departamentos = [
    { id_department: 5, name: 'ANTIOQUIA', id_country: 1 },
    { id_department: 8, name: 'ATLÁNTICO', id_country: 1 },
    { id_department: 11, name: 'BOGOTÁ, D.C.', id_country: 1 },
    { id_department: 13, name: 'BOLÍVAR', id_country: 1 },
    { id_department: 15, name: 'BOYACÁ', id_country: 1 },
    { id_department: 17, name: 'CALDAS', id_country: 1 },
    { id_department: 18, name: 'CAQUETÁ', id_country: 1 },
    { id_department: 19, name: 'CAUCA', id_country: 1 },
    { id_department: 20, name: 'CESAR', id_country: 1 },
    { id_department: 23, name: 'CÓRDOBA', id_country: 1 },
    { id_department: 25, name: 'CUNDINAMARCA', id_country: 1 },
    { id_department: 27, name: 'CHOCÓ', id_country: 1 },
    { id_department: 41, name: 'HUILA', id_country: 1 },
    { id_department: 44, name: 'LA GUAJIRA', id_country: 1 },
    { id_department: 47, name: 'MAGDALENA', id_country: 1 },
    { id_department: 50, name: 'META', id_country: 1 },
    { id_department: 52, name: 'NARIÑO', id_country: 1 },
    { id_department: 54, name: 'NORTE DE SANTANDER', id_country: 1 },
    { id_department: 63, name: 'QUINDÍO', id_country: 1 },
    { id_department: 66, name: 'RISARALDA', id_country: 1 },
    { id_department: 68, name: 'SANTANDER', id_country: 1 },
    { id_department: 70, name: 'SUCRE', id_country: 1 },
    { id_department: 73, name: 'TOLIMA', id_country: 1 },
    { id_department: 76, name: 'VALLE DEL CAUCA', id_country: 1 },
    { id_department: 81, name: 'ARAUCA', id_country: 1 },
    { id_department: 85, name: 'CASANARE', id_country: 1 },
    { id_department: 86, name: 'PUTUMAYO', id_country: 1 },
    { id_department: 88, name: 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', id_country: 1 },
    { id_department: 91, name: 'AMAZONAS', id_country: 1 },
    { id_department: 94, name: 'GUAINÍA', id_country: 1 },
    { id_department: 95, name: 'GUAVIARE', id_country: 1 },
    { id_department: 97, name: 'VAUPÉS', id_country: 1 },
    { id_department: 99, name: 'VICHADA', id_country: 1 }
  ]

  // ?listado de municipios
  const municipios = [
    { id_city: 1, name: 'Abriaquí', id_department: 5 },
    { id_city: 2, name: 'Acacías', id_department: 50 },
    { id_city: 3, name: 'Acandí', id_department: 27 },
    { id_city: 4, name: 'Acevedo', id_department: 41 },
    { id_city: 5, name: 'Achí', id_department: 13 },
    { id_city: 6, name: 'Agrado', id_department: 41 },
    { id_city: 7, name: 'Agua de Dios', id_department: 25 },
    { id_city: 8, name: 'Aguachica', id_department: 20 },
    { id_city: 9, name: 'Aguada', id_department: 68 },
    { id_city: 10, name: 'Aguadas', id_department: 17 },
    { id_city: 11, name: 'Aguazul', id_department: 85 },
    { id_city: 12, name: 'Agustín Codazzi', id_department: 20 },
    { id_city: 13, name: 'Aipe', id_department: 41 },
    { id_city: 14, name: 'Albania', id_department: 18 },
    { id_city: 15, name: 'Albania', id_department: 44 },
    { id_city: 16, name: 'Albania', id_department: 68 },
    { id_city: 17, name: 'Albán', id_department: 25 },
    { id_city: 18, name: 'Albán (San José)', id_department: 52 },
    { id_city: 19, name: 'Alcalá', id_department: 76 },
    { id_city: 20, name: 'Alejandria', id_department: 5 },
    { id_city: 21, name: 'Algarrobo', id_department: 47 },
    { id_city: 22, name: 'Algeciras', id_department: 41 },
    { id_city: 23, name: 'Almaguer', id_department: 19 },
    { id_city: 24, name: 'Almeida', id_department: 15 },
    { id_city: 25, name: 'Alpujarra', id_department: 73 },
    { id_city: 26, name: 'Altamira', id_department: 41 },
    { id_city: 27, name: 'Alto Baudó (Pie de Pato)', id_department: 27 },
    { id_city: 28, name: 'Altos del Rosario', id_department: 13 },
    { id_city: 29, name: 'Alvarado', id_department: 73 },
    { id_city: 30, name: 'Amagá', id_department: 5 },
    { id_city: 31, name: 'Amalfi', id_department: 5 },
    { id_city: 32, name: 'Ambalema', id_department: 73 },
    { id_city: 33, name: 'Anapoima', id_department: 25 },
    { id_city: 34, name: 'Ancuya', id_department: 52 },
    { id_city: 35, name: 'Andalucía', id_department: 76 },
    { id_city: 36, name: 'Andes', id_department: 5 },
    { id_city: 37, name: 'Angelópolis', id_department: 5 },
    { id_city: 38, name: 'Angostura', id_department: 5 },
    { id_city: 39, name: 'Anolaima', id_department: 25 },
    { id_city: 40, name: 'Anorí', id_department: 5 },
    { id_city: 41, name: 'Anserma', id_department: 17 },
    { id_city: 42, name: 'Ansermanuevo', id_department: 76 },
    { id_city: 43, name: 'Anzoátegui', id_department: 73 },
    { id_city: 44, name: 'Anzá', id_department: 5 },
    { id_city: 45, name: 'Apartadó', id_department: 5 },
    { id_city: 46, name: 'Apulo', id_department: 25 },
    { id_city: 47, name: 'Apía', id_department: 66 },
    { id_city: 48, name: 'Aquitania', id_department: 15 },
    { id_city: 49, name: 'Aracataca', id_department: 47 },
    { id_city: 50, name: 'Aranzazu', id_department: 17 },
    { id_city: 51, name: 'Aratoca', id_department: 68 },
    { id_city: 52, name: 'Arauca', id_department: 81 },
    { id_city: 53, name: 'Arauquita', id_department: 81 },
    { id_city: 54, name: 'Arbeláez', id_department: 25 },
    { id_city: 55, name: 'Arboleda (Berruecos)', id_department: 52 },
    { id_city: 56, name: 'Arboledas', id_department: 54 },
    { id_city: 57, name: 'Arboletes', id_department: 5 },
    { id_city: 58, name: 'Arcabuco', id_department: 15 },
    { id_city: 59, name: 'Arenal', id_department: 13 },
    { id_city: 60, name: 'Argelia', id_department: 5 },
    { id_city: 61, name: 'Argelia', id_department: 19 },
    { id_city: 62, name: 'Argelia', id_department: 76 },
    { id_city: 63, name: 'Ariguaní (El Difícil)', id_department: 47 },
    { id_city: 64, name: 'Arjona', id_department: 13 },
    { id_city: 65, name: 'Armenia', id_department: 5 },
    { id_city: 66, name: 'Armenia', id_department: 63 },
    { id_city: 67, name: 'Armero (Guayabal)', id_department: 73 },
    { id_city: 68, name: 'Arroyohondo', id_department: 13 },
    { id_city: 69, name: 'Astrea', id_department: 20 },
    { id_city: 70, name: 'Ataco', id_department: 73 },
    { id_city: 71, name: 'Atrato (Yuto)', id_department: 27 },
    { id_city: 72, name: 'Ayapel', id_department: 23 },
    { id_city: 73, name: 'Bagadó', id_department: 27 },
    { id_city: 74, name: 'Bahía Solano (Mútis)', id_department: 27 },
    { id_city: 75, name: 'Bajo Baudó (Pizarro)', id_department: 27 },
    { id_city: 76, name: 'Balboa', id_department: 19 },
    { id_city: 77, name: 'Balboa', id_department: 66 },
    { id_city: 78, name: 'Baranoa', id_department: 8 },
    { id_city: 79, name: 'Baraya', id_department: 41 },
    { id_city: 80, name: 'Barbacoas', id_department: 52 },
    { id_city: 81, name: 'Barbosa', id_department: 5 },
    { id_city: 82, name: 'Barbosa', id_department: 68 },
    { id_city: 83, name: 'Barichara', id_department: 68 },
    { id_city: 84, name: 'Barranca de Upía', id_department: 50 },
    { id_city: 85, name: 'Barrancabermeja', id_department: 68 },
    { id_city: 86, name: 'Barrancas', id_department: 44 },
    { id_city: 87, name: 'Barranco de Loba', id_department: 13 },
    { id_city: 88, name: 'Barranquilla', id_department: 8 },
    { id_city: 89, name: 'Becerríl', id_department: 20 },
    { id_city: 90, name: 'Belalcázar', id_department: 17 },
    { id_city: 91, name: 'Bello', id_department: 5 },
    { id_city: 92, name: 'Belmira', id_department: 5 },
    { id_city: 93, name: 'Beltrán', id_department: 25 },
    { id_city: 94, name: 'Belén', id_department: 15 },
    { id_city: 95, name: 'Belén', id_department: 52 },
    { id_city: 96, name: 'Belén de Bajirá', id_department: 27 },
    { id_city: 97, name: 'Belén de Umbría', id_department: 66 },
    { id_city: 98, name: 'Belén de los Andaquíes', id_department: 18 },
    { id_city: 99, name: 'Berbeo', id_department: 15 },
    { id_city: 100, name: 'Betania', id_department: 5 },
    { id_city: 101, name: 'Beteitiva', id_department: 15 },
    { id_city: 102, name: 'Betulia', id_department: 5 },
    { id_city: 103, name: 'Betulia', id_department: 68 },
    { id_city: 104, name: 'Bituima', id_department: 25 },
    { id_city: 105, name: 'Boavita', id_department: 15 },
    { id_city: 106, name: 'Bochalema', id_department: 54 },
    { id_city: 107, name: 'Bogotá D.C.', id_department: 11 },
    { id_city: 108, name: 'Bojacá', id_department: 25 },
    { id_city: 109, name: 'Bojayá (Bellavista)', id_department: 27 },
    { id_city: 110, name: 'Bolívar', id_department: 5 },
    { id_city: 111, name: 'Bolívar', id_department: 19 },
    { id_city: 112, name: 'Bolívar', id_department: 68 },
    { id_city: 113, name: 'Bolívar', id_department: 76 },
    { id_city: 114, name: 'Bosconia', id_department: 20 },
    { id_city: 115, name: 'Boyacá', id_department: 15 },
    { id_city: 116, name: 'Briceño', id_department: 5 },
    { id_city: 117, name: 'Briceño', id_department: 15 },
    { id_city: 118, name: 'Bucaramanga', id_department: 68 },
    { id_city: 119, name: 'Bucarasica', id_department: 54 },
    { id_city: 120, name: 'Buenaventura', id_department: 76 },
    { id_city: 121, name: 'Buenavista', id_department: 15 },
    { id_city: 122, name: 'Buenavista', id_department: 23 },
    { id_city: 123, name: 'Buenavista', id_department: 63 },
    { id_city: 124, name: 'Buenavista', id_department: 70 },
    { id_city: 125, name: 'Buenos Aires', id_department: 19 },
    { id_city: 126, name: 'Buesaco', id_department: 52 },
    { id_city: 127, name: 'Buga', id_department: 76 },
    { id_city: 128, name: 'Bugalagrande', id_department: 76 },
    { id_city: 129, name: 'Burítica', id_department: 5 },
    { id_city: 130, name: 'Busbanza', id_department: 15 },
    { id_city: 131, name: 'Cabrera', id_department: 25 },
    { id_city: 132, name: 'Cabrera', id_department: 68 },
    { id_city: 133, name: 'Cabuyaro', id_department: 50 },
    { id_city: 134, name: 'Cachipay', id_department: 25 },
    { id_city: 135, name: 'Caicedo', id_department: 5 },
    { id_city: 136, name: 'Caicedonia', id_department: 76 },
    { id_city: 137, name: 'Caimito', id_department: 70 },
    { id_city: 138, name: 'Cajamarca', id_department: 73 },
    { id_city: 139, name: 'Cajibío', id_department: 19 },
    { id_city: 140, name: 'Cajicá', id_department: 25 },
    { id_city: 141, name: 'Calamar', id_department: 13 },
    { id_city: 142, name: 'Calamar', id_department: 95 },
    { id_city: 143, name: 'Calarcá', id_department: 63 },
    { id_city: 144, name: 'Caldas', id_department: 5 },
    { id_city: 145, name: 'Caldas', id_department: 15 },
    { id_city: 146, name: 'Caldono', id_department: 19 },
    { id_city: 147, name: 'California', id_department: 68 },
    { id_city: 148, name: 'Calima (Darién)', id_department: 76 },
    { id_city: 149, name: 'Caloto', id_department: 19 },
    { id_city: 150, name: 'Calí', id_department: 76 },
    { id_city: 151, name: 'Campamento', id_department: 5 },
    { id_city: 152, name: 'Campo de la Cruz', id_department: 8 },
    { id_city: 153, name: 'Campoalegre', id_department: 41 },
    { id_city: 154, name: 'Campohermoso', id_department: 15 },
    { id_city: 155, name: 'Canalete', id_department: 23 },
    { id_city: 156, name: 'Candelaria', id_department: 8 },
    { id_city: 157, name: 'Candelaria', id_department: 76 },
    { id_city: 158, name: 'Cantagallo', id_department: 13 },
    { id_city: 159, name: 'Cantón de San Pablo', id_department: 27 },
    { id_city: 160, name: 'Caparrapí', id_department: 25 },
    { id_city: 161, name: 'Capitanejo', id_department: 68 },
    { id_city: 162, name: 'Caracolí', id_department: 5 },
    { id_city: 163, name: 'Caramanta', id_department: 5 },
    { id_city: 164, name: 'Carcasí', id_department: 68 },
    { id_city: 165, name: 'Carepa', id_department: 5 },
    { id_city: 166, name: 'Carmen de Apicalá', id_department: 73 },
    { id_city: 167, name: 'Carmen de Carupa', id_department: 25 },
    { id_city: 168, name: 'Carmen de Viboral', id_department: 5 },
    { id_city: 169, name: 'Carmen del Darién (CURBARADÓ)', id_department: 27 },
    { id_city: 170, name: 'Carolina', id_department: 5 },
    { id_city: 171, name: 'Cartagena', id_department: 13 },
    { id_city: 172, name: 'Cartagena del Chairá', id_department: 18 },
    { id_city: 173, name: 'Cartago', id_department: 76 },
    { id_city: 174, name: 'Carurú', id_department: 97 },
    { id_city: 175, name: 'Casabianca', id_department: 73 },
    { id_city: 176, name: 'Castilla la Nueva', id_department: 50 },
    { id_city: 177, name: 'Caucasia', id_department: 5 },
    { id_city: 178, name: 'Cañasgordas', id_department: 5 },
    { id_city: 179, name: 'Cepita', id_department: 68 },
    { id_city: 180, name: 'Cereté', id_department: 23 },
    { id_city: 181, name: 'Cerinza', id_department: 15 },
    { id_city: 182, name: 'Cerrito', id_department: 68 },
    { id_city: 183, name: 'Cerro San Antonio', id_department: 47 },
    { id_city: 184, name: 'Chachaguí', id_department: 52 },
    { id_city: 185, name: 'Chaguaní', id_department: 25 },
    { id_city: 186, name: 'Chalán', id_department: 70 },
    { id_city: 187, name: 'Chaparral', id_department: 73 },
    { id_city: 188, name: 'Charalá', id_department: 68 },
    { id_city: 189, name: 'Charta', id_department: 68 },
    { id_city: 190, name: 'Chigorodó', id_department: 5 },
    { id_city: 191, name: 'Chima', id_department: 68 },
    { id_city: 192, name: 'Chimichagua', id_department: 20 },
    { id_city: 193, name: 'Chimá', id_department: 23 },
    { id_city: 194, name: 'Chinavita', id_department: 15 },
    { id_city: 195, name: 'Chinchiná', id_department: 17 },
    { id_city: 196, name: 'Chinácota', id_department: 54 },
    { id_city: 197, name: 'Chinú', id_department: 23 },
    { id_city: 198, name: 'Chipaque', id_department: 25 },
    { id_city: 199, name: 'Chipatá', id_department: 68 },
    { id_city: 200, name: 'Chiquinquirá', id_department: 15 },
    { id_city: 201, name: 'Chiriguaná', id_department: 20 },
    { id_city: 202, name: 'Chiscas', id_department: 15 },
    { id_city: 203, name: 'Chita', id_department: 15 },
    { id_city: 204, name: 'Chitagá', id_department: 54 },
    { id_city: 205, name: 'Chitaraque', id_department: 15 },
    { id_city: 206, name: 'Chivatá', id_department: 15 },
    { id_city: 207, name: 'Chivolo', id_department: 47 },
    { id_city: 208, name: 'Choachí', id_department: 25 },
    { id_city: 209, name: 'Chocontá', id_department: 25 },
    { id_city: 210, name: 'Chámeza', id_department: 85 },
    { id_city: 211, name: 'Chía', id_department: 25 },
    { id_city: 212, name: 'Chíquiza', id_department: 15 },
    { id_city: 213, name: 'Chívor', id_department: 15 },
    { id_city: 214, name: 'Cicuco', id_department: 13 },
    { id_city: 215, name: 'Cimitarra', id_department: 68 },
    { id_city: 216, name: 'Circasia', id_department: 63 },
    { id_city: 217, name: 'Cisneros', id_department: 5 },
    { id_city: 218, name: 'Ciénaga', id_department: 15 },
    { id_city: 219, name: 'Ciénaga', id_department: 47 },
    { id_city: 220, name: 'Ciénaga de Oro', id_department: 23 },
    { id_city: 221, name: 'Clemencia', id_department: 13 },
    { id_city: 222, name: 'Cocorná', id_department: 5 },
    { id_city: 223, name: 'Coello', id_department: 73 },
    { id_city: 224, name: 'Cogua', id_department: 25 },
    { id_city: 225, name: 'Colombia', id_department: 41 },
    { id_city: 226, name: 'Colosó (Ricaurte)', id_department: 70 },
    { id_city: 227, name: 'Colón', id_department: 86 },
    { id_city: 228, name: 'Colón (Génova)', id_department: 52 },
    { id_city: 229, name: 'Concepción', id_department: 5 },
    { id_city: 230, name: 'Concepción', id_department: 68 },
    { id_city: 231, name: 'Concordia', id_department: 5 },
    { id_city: 232, name: 'Concordia', id_department: 47 },
    { id_city: 233, name: 'Condoto', id_department: 27 },
    { id_city: 234, name: 'Confines', id_department: 68 },
    { id_city: 235, name: 'Consaca', id_department: 52 },
    { id_city: 236, name: 'Contadero', id_department: 52 },
    { id_city: 237, name: 'Contratación', id_department: 68 },
    { id_city: 238, name: 'Convención', id_department: 54 },
    { id_city: 239, name: 'Copacabana', id_department: 5 },
    { id_city: 240, name: 'Coper', id_department: 15 },
    { id_city: 241, name: 'Cordobá', id_department: 63 },
    { id_city: 242, name: 'Corinto', id_department: 19 },
    { id_city: 243, name: 'Coromoro', id_department: 68 },
    { id_city: 244, name: 'Corozal', id_department: 70 },
    { id_city: 245, name: 'Corrales', id_department: 15 },
    { id_city: 246, name: 'Cota', id_department: 25 },
    { id_city: 247, name: 'Cotorra', id_department: 23 },
    { id_city: 248, name: 'Covarachía', id_department: 15 },
    { id_city: 249, name: 'Coveñas', id_department: 70 },
    { id_city: 250, name: 'Coyaima', id_department: 73 },
    { id_city: 251, name: 'Cravo Norte', id_department: 81 },
    { id_city: 252, name: 'Cuaspud (Carlosama)', id_department: 52 },
    { id_city: 253, name: 'Cubarral', id_department: 50 },
    { id_city: 254, name: 'Cubará', id_department: 15 },
    { id_city: 255, name: 'Cucaita', id_department: 15 },
    { id_city: 256, name: 'Cucunubá', id_department: 25 },
    { id_city: 257, name: 'Cucutilla', id_department: 54 },
    { id_city: 258, name: 'Cuitiva', id_department: 15 },
    { id_city: 259, name: 'Cumaral', id_department: 50 },
    { id_city: 260, name: 'Cumaribo', id_department: 99 },
    { id_city: 261, name: 'Cumbal', id_department: 52 },
    { id_city: 262, name: 'Cumbitara', id_department: 52 },
    { id_city: 263, name: 'Cunday', id_department: 73 },
    { id_city: 264, name: 'Curillo', id_department: 18 },
    { id_city: 265, name: 'Curití', id_department: 68 },
    { id_city: 266, name: 'Curumaní', id_department: 20 },
    { id_city: 267, name: 'Cáceres', id_department: 5 },
    { id_city: 268, name: 'Cáchira', id_department: 54 },
    { id_city: 269, name: 'Cácota', id_department: 54 },
    { id_city: 270, name: 'Cáqueza', id_department: 25 },
    { id_city: 271, name: 'Cértegui', id_department: 27 },
    { id_city: 272, name: 'Cómbita', id_department: 15 },
    { id_city: 273, name: 'Córdoba', id_department: 13 },
    { id_city: 274, name: 'Córdoba', id_department: 52 },
    { id_city: 275, name: 'Cúcuta', id_department: 54 },
    { id_city: 276, name: 'Dabeiba', id_department: 5 },
    { id_city: 277, name: 'Dagua', id_department: 76 },
    { id_city: 278, name: 'Dibulla', id_department: 44 },
    { id_city: 279, name: 'Distracción', id_department: 44 },
    { id_city: 280, name: 'Dolores', id_department: 73 },
    { id_city: 281, name: 'Don Matías', id_department: 5 },
    { id_city: 282, name: 'Dos Quebradas', id_department: 66 },
    { id_city: 283, name: 'Duitama', id_department: 15 },
    { id_city: 284, name: 'Durania', id_department: 54 },
    { id_city: 285, name: 'Ebéjico', id_department: 5 },
    { id_city: 286, name: 'El Bagre', id_department: 5 },
    { id_city: 287, name: 'El Banco', id_department: 47 },
    { id_city: 288, name: 'El Cairo', id_department: 76 },
    { id_city: 289, name: 'El Calvario', id_department: 50 },
    { id_city: 290, name: 'El Carmen', id_department: 54 },
    { id_city: 291, name: 'El Carmen', id_department: 68 },
    { id_city: 292, name: 'El Carmen de Atrato', id_department: 27 },
    { id_city: 293, name: 'El Carmen de Bolívar', id_department: 13 },
    { id_city: 294, name: 'El Castillo', id_department: 50 },
    { id_city: 295, name: 'El Cerrito', id_department: 76 },
    { id_city: 296, name: 'El Charco', id_department: 52 },
    { id_city: 297, name: 'El Cocuy', id_department: 15 },
    { id_city: 298, name: 'El Colegio', id_department: 25 },
    { id_city: 299, name: 'El Copey', id_department: 20 },
    { id_city: 300, name: 'El Doncello', id_department: 18 },
    { id_city: 301, name: 'El Dorado', id_department: 50 },
    { id_city: 302, name: 'El Dovio', id_department: 76 },
    { id_city: 303, name: 'El Espino', id_department: 15 },
    { id_city: 304, name: 'El Guacamayo', id_department: 68 },
    { id_city: 305, name: 'El Guamo', id_department: 13 },
    { id_city: 306, name: 'El Molino', id_department: 44 },
    { id_city: 307, name: 'El Paso', id_department: 20 },
    { id_city: 308, name: 'El Paujil', id_department: 18 },
    { id_city: 309, name: 'El Peñol', id_department: 52 },
    { id_city: 310, name: 'El Peñon', id_department: 13 },
    { id_city: 311, name: 'El Peñon', id_department: 68 },
    { id_city: 312, name: 'El Peñón', id_department: 25 },
    { id_city: 313, name: 'El Piñon', id_department: 47 },
    { id_city: 314, name: 'El Playón', id_department: 68 },
    { id_city: 315, name: 'El Retorno', id_department: 95 },
    { id_city: 316, name: 'El Retén', id_department: 47 },
    { id_city: 317, name: 'El Roble', id_department: 70 },
    { id_city: 318, name: 'El Rosal', id_department: 25 },
    { id_city: 319, name: 'El Rosario', id_department: 52 },
    { id_city: 320, name: 'El Tablón de Gómez', id_department: 52 },
    { id_city: 321, name: 'El Tambo', id_department: 19 },
    { id_city: 322, name: 'El Tambo', id_department: 52 },
    { id_city: 323, name: 'El Tarra', id_department: 54 },
    { id_city: 324, name: 'El Zulia', id_department: 54 },
    { id_city: 325, name: 'El Águila', id_department: 76 },
    { id_city: 326, name: 'Elías', id_department: 41 },
    { id_city: 327, name: 'Encino', id_department: 68 },
    { id_city: 328, name: 'Enciso', id_department: 68 },
    { id_city: 329, name: 'Entrerríos', id_department: 5 },
    { id_city: 330, name: 'Envigado', id_department: 5 },
    { id_city: 331, name: 'Espinal', id_department: 73 },
    { id_city: 332, name: 'Facatativá', id_department: 25 },
    { id_city: 333, name: 'Falan', id_department: 73 },
    { id_city: 334, name: 'Filadelfia', id_department: 17 },
    { id_city: 335, name: 'Filandia', id_department: 63 },
    { id_city: 336, name: 'Firavitoba', id_department: 15 },
    { id_city: 337, name: 'Flandes', id_department: 73 },
    { id_city: 338, name: 'Florencia', id_department: 18 },
    { id_city: 339, name: 'Florencia', id_department: 19 },
    { id_city: 340, name: 'Floresta', id_department: 15 },
    { id_city: 341, name: 'Florida', id_department: 76 },
    { id_city: 342, name: 'Floridablanca', id_department: 68 },
    { id_city: 343, name: 'Florián', id_department: 68 },
    { id_city: 344, name: 'Fonseca', id_department: 44 },
    { id_city: 345, name: 'Fortúl', id_department: 81 },
    { id_city: 346, name: 'Fosca', id_department: 25 },
    { id_city: 347, name: 'Francisco Pizarro', id_department: 52 },
    { id_city: 348, name: 'Fredonia', id_department: 5 },
    { id_city: 349, name: 'Fresno', id_department: 73 },
    { id_city: 350, name: 'Frontino', id_department: 5 },
    { id_city: 351, name: 'Fuente de Oro', id_department: 50 },
    { id_city: 352, name: 'Fundación', id_department: 47 },
    { id_city: 353, name: 'Funes', id_department: 52 },
    { id_city: 354, name: 'Funza', id_department: 25 },
    { id_city: 355, name: 'Fusagasugá', id_department: 25 },
    { id_city: 356, name: 'Fómeque', id_department: 25 },
    { id_city: 357, name: 'Fúquene', id_department: 25 },
    { id_city: 358, name: 'Gachalá', id_department: 25 },
    { id_city: 359, name: 'Gachancipá', id_department: 25 },
    { id_city: 360, name: 'Gachantivá', id_department: 15 },
    { id_city: 361, name: 'Gachetá', id_department: 25 },
    { id_city: 362, name: 'Galapa', id_department: 8 },
    { id_city: 363, name: 'Galeras (Nueva Granada)', id_department: 70 },
    { id_city: 364, name: 'Galán', id_department: 68 },
    { id_city: 365, name: 'Gama', id_department: 25 },
    { id_city: 366, name: 'Gamarra', id_department: 20 },
    { id_city: 367, name: 'Garagoa', id_department: 15 },
    { id_city: 368, name: 'Garzón', id_department: 41 },
    { id_city: 369, name: 'Gigante', id_department: 41 },
    { id_city: 370, name: 'Ginebra', id_department: 76 },
    { id_city: 371, name: 'Giraldo', id_department: 5 },
    { id_city: 372, name: 'Girardot', id_department: 25 },
    { id_city: 373, name: 'Girardota', id_department: 5 },
    { id_city: 374, name: 'Girón', id_department: 68 },
    { id_city: 375, name: 'Gonzalez', id_department: 20 },
    { id_city: 376, name: 'Gramalote', id_department: 54 },
    { id_city: 377, name: 'Granada', id_department: 5 },
    { id_city: 378, name: 'Granada', id_department: 25 },
    { id_city: 379, name: 'Granada', id_department: 50 },
    { id_city: 380, name: 'Guaca', id_department: 68 },
    { id_city: 381, name: 'Guacamayas', id_department: 15 },
    { id_city: 382, name: 'Guacarí', id_department: 76 },
    { id_city: 383, name: 'Guachavés', id_department: 52 },
    { id_city: 384, name: 'Guachené', id_department: 19 },
    { id_city: 385, name: 'Guachetá', id_department: 25 },
    { id_city: 386, name: 'Guachucal', id_department: 52 },
    { id_city: 387, name: 'Guadalupe', id_department: 5 },
    { id_city: 388, name: 'Guadalupe', id_department: 41 },
    { id_city: 389, name: 'Guadalupe', id_department: 68 },
    { id_city: 390, name: 'Guaduas', id_department: 25 },
    { id_city: 391, name: 'Guaitarilla', id_department: 52 },
    { id_city: 392, name: 'Gualmatán', id_department: 52 },
    { id_city: 393, name: 'Guamal', id_department: 47 },
    { id_city: 394, name: 'Guamal', id_department: 50 },
    { id_city: 395, name: 'Guamo', id_department: 73 },
    { id_city: 396, name: 'Guapota', id_department: 68 },
    { id_city: 397, name: 'Guapí', id_department: 19 },
    { id_city: 398, name: 'Guaranda', id_department: 70 },
    { id_city: 399, name: 'Guarne', id_department: 5 },
    { id_city: 400, name: 'Guasca', id_department: 25 },
    { id_city: 401, name: 'Guatapé', id_department: 5 },
    { id_city: 402, name: 'Guataquí', id_department: 25 },
    { id_city: 403, name: 'Guatavita', id_department: 25 },
    { id_city: 404, name: 'Guateque', id_department: 15 },
    { id_city: 405, name: 'Guavatá', id_department: 68 },
    { id_city: 406, name: 'Guayabal de Siquima', id_department: 25 },
    { id_city: 407, name: 'Guayabetal', id_department: 25 },
    { id_city: 408, name: 'Guayatá', id_department: 15 },
    { id_city: 409, name: 'Guepsa', id_department: 68 },
    { id_city: 410, name: 'Guicán', id_department: 15 },
    { id_city: 411, name: 'Gutiérrez', id_department: 25 },
    { id_city: 412, name: 'Guática', id_department: 66 },
    { id_city: 413, name: 'Gámbita', id_department: 68 },
    { id_city: 414, name: 'Gámeza', id_department: 15 },
    { id_city: 415, name: 'Génova', id_department: 63 },
    { id_city: 416, name: 'Gómez Plata', id_department: 5 },
    { id_city: 417, name: 'Hacarí', id_department: 54 },
    { id_city: 418, name: 'Hatillo de Loba', id_department: 13 },
    { id_city: 419, name: 'Hato', id_department: 68 },
    { id_city: 420, name: 'Hato Corozal', id_department: 85 },
    { id_city: 421, name: 'Hatonuevo', id_department: 44 },
    { id_city: 422, name: 'Heliconia', id_department: 5 },
    { id_city: 423, name: 'Herrán', id_department: 54 },
    { id_city: 424, name: 'Herveo', id_department: 73 },
    { id_city: 425, name: 'Hispania', id_department: 5 },
    { id_city: 426, name: 'Hobo', id_department: 41 },
    { id_city: 427, name: 'Honda', id_department: 73 },
    { id_city: 428, name: 'Ibagué', id_department: 73 },
    { id_city: 429, name: 'Icononzo', id_department: 73 },
    { id_city: 430, name: 'Iles', id_department: 52 },
    { id_city: 431, name: 'Imúes', id_department: 52 },
    { id_city: 432, name: 'Inzá', id_department: 19 },
    { id_city: 433, name: 'Inírida', id_department: 94 },
    { id_city: 434, name: 'Ipiales', id_department: 52 },
    { id_city: 435, name: 'Isnos', id_department: 41 },
    { id_city: 436, name: 'Istmina', id_department: 27 },
    { id_city: 437, name: 'Itagüí', id_department: 5 },
    { id_city: 438, name: 'Ituango', id_department: 5 },
    { id_city: 439, name: 'Izá', id_department: 15 },
    { id_city: 440, name: 'Jambaló', id_department: 19 },
    { id_city: 441, name: 'Jamundí', id_department: 76 },
    { id_city: 442, name: 'Jardín', id_department: 5 },
    { id_city: 443, name: 'Jenesano', id_department: 15 },
    { id_city: 444, name: 'Jericó', id_department: 5 },
    { id_city: 445, name: 'Jericó', id_department: 15 },
    { id_city: 446, name: 'Jerusalén', id_department: 25 },
    { id_city: 447, name: 'Jesús María', id_department: 68 },
    { id_city: 448, name: 'Jordán', id_department: 68 },
    { id_city: 449, name: 'Juan de Acosta', id_department: 8 },
    { id_city: 450, name: 'Junín', id_department: 25 },
    { id_city: 451, name: 'Juradó', id_department: 27 },
    { id_city: 452, name: 'La Apartada y La Frontera', id_department: 23 },
    { id_city: 453, name: 'La Argentina', id_department: 41 },
    { id_city: 454, name: 'La Belleza', id_department: 68 },
    { id_city: 455, name: 'La Calera', id_department: 25 },
    { id_city: 456, name: 'La Capilla', id_department: 15 },
    { id_city: 457, name: 'La Ceja', id_department: 5 },
    { id_city: 458, name: 'La Celia', id_department: 66 },
    { id_city: 459, name: 'La Cruz', id_department: 52 },
    { id_city: 460, name: 'La Cumbre', id_department: 76 },
    { id_city: 461, name: 'La Dorada', id_department: 17 },
    { id_city: 462, name: 'La Esperanza', id_department: 54 },
    { id_city: 463, name: 'La Estrella', id_department: 5 },
    { id_city: 464, name: 'La Florida', id_department: 52 },
    { id_city: 465, name: 'La Gloria', id_department: 20 },
    { id_city: 466, name: 'La Jagua de Ibirico', id_department: 20 },
    { id_city: 467, name: 'La Jagua del Pilar', id_department: 44 },
    { id_city: 468, name: 'La Llanada', id_department: 52 },
    { id_city: 469, name: 'La Macarena', id_department: 50 },
    { id_city: 470, name: 'La Merced', id_department: 17 },
    { id_city: 471, name: 'La Mesa', id_department: 25 },
    { id_city: 472, name: 'La Montañita', id_department: 18 },
    { id_city: 473, name: 'La Palma', id_department: 25 },
    { id_city: 474, name: 'La Paz', id_department: 68 },
    { id_city: 475, name: 'La Paz (Robles)', id_department: 20 },
    { id_city: 476, name: 'La Peña', id_department: 25 },
    { id_city: 477, name: 'La Pintada', id_department: 5 },
    { id_city: 478, name: 'La Plata', id_department: 41 },
    { id_city: 479, name: 'La Playa', id_department: 54 },
    { id_city: 480, name: 'La Primavera', id_department: 99 },
    { id_city: 481, name: 'La Salina', id_department: 85 },
    { id_city: 482, name: 'La Sierra', id_department: 19 },
    { id_city: 483, name: 'La Tebaida', id_department: 63 },
    { id_city: 484, name: 'La Tola', id_department: 52 },
    { id_city: 485, name: 'La Unión', id_department: 5 },
    { id_city: 486, name: 'La Unión', id_department: 52 },
    { id_city: 487, name: 'La Unión', id_department: 70 },
    { id_city: 488, name: 'La Unión', id_department: 76 },
    { id_city: 489, name: 'La Uvita', id_department: 15 },
    { id_city: 490, name: 'La Vega', id_department: 19 },
    { id_city: 491, name: 'La Vega', id_department: 25 },
    { id_city: 492, name: 'La Victoria', id_department: 15 },
    { id_city: 493, name: 'La Victoria', id_department: 17 },
    { id_city: 494, name: 'La Victoria', id_department: 76 },
    { id_city: 495, name: 'La Virginia', id_department: 66 },
    { id_city: 496, name: 'Labateca', id_department: 54 },
    { id_city: 497, name: 'Labranzagrande', id_department: 15 },
    { id_city: 498, name: 'Landázuri', id_department: 68 },
    { id_city: 499, name: 'Lebrija', id_department: 68 },
    { id_city: 500, name: 'Leiva', id_department: 52 },
    { id_city: 501, name: 'Lejanías', id_department: 50 },
    { id_city: 502, name: 'Lenguazaque', id_department: 25 },
    { id_city: 503, name: 'Leticia', id_department: 91 },
    { id_city: 504, name: 'Liborina', id_department: 5 },
    { id_city: 505, name: 'Linares', id_department: 52 },
    { id_city: 506, name: 'Lloró', id_department: 27 },
    { id_city: 507, name: 'Lorica', id_department: 23 },
    { id_city: 508, name: 'Los Córdobas', id_department: 23 },
    { id_city: 509, name: 'Los Palmitos', id_department: 70 },
    { id_city: 510, name: 'Los Patios', id_department: 54 },
    { id_city: 511, name: 'Los Santos', id_department: 68 },
    { id_city: 512, name: 'Lourdes', id_department: 54 },
    { id_city: 513, name: 'Luruaco', id_department: 8 },
    { id_city: 514, name: 'Lérida', id_department: 73 },
    { id_city: 515, name: 'Líbano', id_department: 73 },
    { id_city: 516, name: 'López (Micay)', id_department: 19 },
    { id_city: 517, name: 'Macanal', id_department: 15 },
    { id_city: 518, name: 'Macaravita', id_department: 68 },
    { id_city: 519, name: 'Maceo', id_department: 5 },
    { id_city: 520, name: 'Machetá', id_department: 25 },
    { id_city: 521, name: 'Madrid', id_department: 25 },
    { id_city: 522, name: 'Magangué', id_department: 13 },
    { id_city: 523, name: 'Magüi (Payán)', id_department: 52 },
    { id_city: 524, name: 'Mahates', id_department: 13 },
    { id_city: 525, name: 'Maicao', id_department: 44 },
    { id_city: 526, name: 'Majagual', id_department: 70 },
    { id_city: 527, name: 'Malambo', id_department: 8 },
    { id_city: 528, name: 'Mallama (Piedrancha)', id_department: 52 },
    { id_city: 529, name: 'Manatí', id_department: 8 },
    { id_city: 530, name: 'Manaure', id_department: 44 },
    { id_city: 531, name: 'Manaure Balcón del Cesar', id_department: 20 },
    { id_city: 532, name: 'Manizales', id_department: 17 },
    { id_city: 533, name: 'Manta', id_department: 25 },
    { id_city: 534, name: 'Manzanares', id_department: 17 },
    { id_city: 535, name: 'Maní', id_department: 85 },
    { id_city: 536, name: 'Mapiripan', id_department: 50 },
    { id_city: 537, name: 'Margarita', id_department: 13 },
    { id_city: 538, name: 'Marinilla', id_department: 5 },
    { id_city: 539, name: 'Maripí', id_department: 15 },
    { id_city: 540, name: 'Mariquita', id_department: 73 },
    { id_city: 541, name: 'Marmato', id_department: 17 },
    { id_city: 542, name: 'Marquetalia', id_department: 17 },
    { id_city: 543, name: 'Marsella', id_department: 66 },
    { id_city: 544, name: 'Marulanda', id_department: 17 },
    { id_city: 545, name: 'María la Baja', id_department: 13 },
    { id_city: 546, name: 'Matanza', id_department: 68 },
    { id_city: 547, name: 'Medellín', id_department: 5 },
    { id_city: 548, name: 'Medina', id_department: 25 },
    { id_city: 549, name: 'Medio Atrato', id_department: 27 },
    { id_city: 550, name: 'Medio Baudó', id_department: 27 },
    { id_city: 551, name: 'Medio San Juan (ANDAGOYA)', id_department: 27 },
    { id_city: 552, name: 'Melgar', id_department: 73 },
    { id_city: 553, name: 'Mercaderes', id_department: 19 },
    { id_city: 554, name: 'Mesetas', id_department: 50 },
    { id_city: 555, name: 'Milán', id_department: 18 },
    { id_city: 556, name: 'Miraflores', id_department: 15 },
    { id_city: 557, name: 'Miraflores', id_department: 95 },
    { id_city: 558, name: 'Miranda', id_department: 19 },
    { id_city: 559, name: 'Mistrató', id_department: 66 },
    { id_city: 560, name: 'Mitú', id_department: 97 },
    { id_city: 561, name: 'Mocoa', id_department: 86 },
    { id_city: 562, name: 'Mogotes', id_department: 68 },
    { id_city: 563, name: 'Molagavita', id_department: 68 },
    { id_city: 564, name: 'Momil', id_department: 23 },
    { id_city: 565, name: 'Mompós', id_department: 13 },
    { id_city: 566, name: 'Mongua', id_department: 15 },
    { id_city: 567, name: 'Monguí', id_department: 15 },
    { id_city: 568, name: 'Moniquirá', id_department: 15 },
    { id_city: 569, name: 'Montebello', id_department: 5 },
    { id_city: 570, name: 'Montecristo', id_department: 13 },
    { id_city: 571, name: 'Montelíbano', id_department: 23 },
    { id_city: 572, name: 'Montenegro', id_department: 63 },
    { id_city: 573, name: 'Monteria', id_department: 23 },
    { id_city: 574, name: 'Monterrey', id_department: 85 },
    { id_city: 575, name: 'Morales', id_department: 13 },
    { id_city: 576, name: 'Morales', id_department: 19 },
    { id_city: 577, name: 'Morelia', id_department: 18 },
    { id_city: 578, name: 'Morroa', id_department: 70 },
    { id_city: 579, name: 'Mosquera', id_department: 25 },
    { id_city: 580, name: 'Mosquera', id_department: 52 },
    { id_city: 581, name: 'Motavita', id_department: 15 },
    { id_city: 582, name: 'Moñitos', id_department: 23 },
    { id_city: 583, name: 'Murillo', id_department: 73 },
    { id_city: 584, name: 'Murindó', id_department: 5 },
    { id_city: 585, name: 'Mutatá', id_department: 5 },
    { id_city: 586, name: 'Mutiscua', id_department: 54 },
    { id_city: 587, name: 'Muzo', id_department: 15 },
    { id_city: 588, name: 'Málaga', id_department: 68 },
    { id_city: 589, name: 'Nariño', id_department: 5 },
    { id_city: 590, name: 'Nariño', id_department: 25 },
    { id_city: 591, name: 'Nariño', id_department: 52 },
    { id_city: 592, name: 'Natagaima', id_department: 73 },
    { id_city: 593, name: 'Nechí', id_department: 5 },
    { id_city: 594, name: 'Necoclí', id_department: 5 },
    { id_city: 595, name: 'Neira', id_department: 17 },
    { id_city: 596, name: 'Neiva', id_department: 41 },
    { id_city: 597, name: 'Nemocón', id_department: 25 },
    { id_city: 598, name: 'Nilo', id_department: 25 },
    { id_city: 599, name: 'Nimaima', id_department: 25 },
    { id_city: 600, name: 'Nobsa', id_department: 15 },
    { id_city: 601, name: 'Nocaima', id_department: 25 },
    { id_city: 602, name: 'Norcasia', id_department: 17 },
    { id_city: 603, name: 'Norosí', id_department: 13 },
    { id_city: 604, name: 'Novita', id_department: 27 },
    { id_city: 605, name: 'Nueva Granada', id_department: 47 },
    { id_city: 606, name: 'Nuevo Colón', id_department: 15 },
    { id_city: 607, name: 'Nunchía', id_department: 85 },
    { id_city: 608, name: 'Nuquí', id_department: 27 },
    { id_city: 609, name: 'Nátaga', id_department: 41 },
    { id_city: 610, name: 'Obando', id_department: 76 },
    { id_city: 611, name: 'Ocamonte', id_department: 68 },
    { id_city: 612, name: 'Ocaña', id_department: 54 },
    { id_city: 613, name: 'Oiba', id_department: 68 },
    { id_city: 614, name: 'Oicatá', id_department: 15 },
    { id_city: 615, name: 'Olaya', id_department: 5 },
    { id_city: 616, name: 'Olaya Herrera', id_department: 52 },
    { id_city: 617, name: 'Onzaga', id_department: 68 },
    { id_city: 618, name: 'Oporapa', id_department: 41 },
    { id_city: 619, name: 'Orito', id_department: 86 },
    { id_city: 620, name: 'Orocué', id_department: 85 },
    { id_city: 621, name: 'Ortega', id_department: 73 },
    { id_city: 622, name: 'Ospina', id_department: 52 },
    { id_city: 623, name: 'Otanche', id_department: 15 },
    { id_city: 624, name: 'Ovejas', id_department: 70 },
    { id_city: 625, name: 'Pachavita', id_department: 15 },
    { id_city: 626, name: 'Pacho', id_department: 25 },
    { id_city: 627, name: 'Padilla', id_department: 19 },
    { id_city: 628, name: 'Paicol', id_department: 41 },
    { id_city: 629, name: 'Pailitas', id_department: 20 },
    { id_city: 630, name: 'Paime', id_department: 25 },
    { id_city: 631, name: 'Paipa', id_department: 15 },
    { id_city: 632, name: 'Pajarito', id_department: 15 },
    { id_city: 633, name: 'Palermo', id_department: 41 },
    { id_city: 634, name: 'Palestina', id_department: 17 },
    { id_city: 635, name: 'Palestina', id_department: 41 },
    { id_city: 636, name: 'Palmar', id_department: 68 },
    { id_city: 637, name: 'Palmar de Varela', id_department: 8 },
    { id_city: 638, name: 'Palmas del Socorro', id_department: 68 },
    { id_city: 639, name: 'Palmira', id_department: 76 },
    { id_city: 640, name: 'Palmito', id_department: 70 },
    { id_city: 641, name: 'Palocabildo', id_department: 73 },
    { id_city: 642, name: 'Pamplona', id_department: 54 },
    { id_city: 643, name: 'Pamplonita', id_department: 54 },
    { id_city: 644, name: 'Pandi', id_department: 25 },
    { id_city: 645, name: 'Panqueba', id_department: 15 },
    { id_city: 646, name: 'Paratebueno', id_department: 25 },
    { id_city: 647, name: 'Pasca', id_department: 25 },
    { id_city: 648, name: 'Patía (El Bordo)', id_department: 19 },
    { id_city: 649, name: 'Pauna', id_department: 15 },
    { id_city: 650, name: 'Paya', id_department: 15 },
    { id_city: 651, name: 'Paz de Ariporo', id_department: 85 },
    { id_city: 652, name: 'Paz de Río', id_department: 15 },
    { id_city: 653, name: 'Pedraza', id_department: 47 },
    { id_city: 654, name: 'Pelaya', id_department: 20 },
    { id_city: 655, name: 'Pensilvania', id_department: 17 },
    { id_city: 656, name: 'Peque', id_department: 5 },
    { id_city: 657, name: 'Pereira', id_department: 66 },
    { id_city: 658, name: 'Pesca', id_department: 15 },
    { id_city: 659, name: 'Peñol', id_department: 5 },
    { id_city: 660, name: 'Piamonte', id_department: 19 },
    { id_city: 661, name: 'Pie de Cuesta', id_department: 68 },
    { id_city: 662, name: 'Piedras', id_department: 73 },
    { id_city: 663, name: 'Piendamó', id_department: 19 },
    { id_city: 664, name: 'Pijao', id_department: 63 },
    { id_city: 665, name: 'Pijiño', id_department: 47 },
    { id_city: 666, name: 'Pinchote', id_department: 68 },
    { id_city: 667, name: 'Pinillos', id_department: 13 },
    { id_city: 668, name: 'Piojo', id_department: 8 },
    { id_city: 669, name: 'Pisva', id_department: 15 },
    { id_city: 670, name: 'Pital', id_department: 41 },
    { id_city: 671, name: 'Pitalito', id_department: 41 },
    { id_city: 672, name: 'Pivijay', id_department: 47 },
    { id_city: 673, name: 'Planadas', id_department: 73 },
    { id_city: 674, name: 'Planeta Rica', id_department: 23 },
    { id_city: 675, name: 'Plato', id_department: 47 },
    { id_city: 676, name: 'Policarpa', id_department: 52 },
    { id_city: 677, name: 'Polonuevo', id_department: 8 },
    { id_city: 678, name: 'Ponedera', id_department: 8 },
    { id_city: 679, name: 'Popayán', id_department: 19 },
    { id_city: 680, name: 'Pore', id_department: 85 },
    { id_city: 681, name: 'Potosí', id_department: 52 },
    { id_city: 682, name: 'Pradera', id_department: 76 },
    { id_city: 683, name: 'Prado', id_department: 73 },
    { id_city: 684, name: 'Providencia', id_department: 52 },
    { id_city: 685, name: 'Providencia', id_department: 88 },
    { id_city: 686, name: 'Pueblo Bello', id_department: 20 },
    { id_city: 687, name: 'Pueblo Nuevo', id_department: 23 },
    { id_city: 688, name: 'Pueblo Rico', id_department: 66 },
    { id_city: 689, name: 'Pueblorrico', id_department: 5 },
    { id_city: 690, name: 'Puebloviejo', id_department: 47 },
    { id_city: 691, name: 'Puente Nacional', id_department: 68 },
    { id_city: 692, name: 'Puerres', id_department: 52 },
    { id_city: 693, name: 'Puerto Asís', id_department: 86 },
    { id_city: 694, name: 'Puerto Berrío', id_department: 5 },
    { id_city: 695, name: 'Puerto Boyacá', id_department: 15 },
    { id_city: 696, name: 'Puerto Caicedo', id_department: 86 },
    { id_city: 697, name: 'Puerto Carreño', id_department: 99 },
    { id_city: 698, name: 'Puerto Colombia', id_department: 8 },
    { id_city: 699, name: 'Puerto Concordia', id_department: 50 },
    { id_city: 700, name: 'Puerto Escondido', id_department: 23 },
    { id_city: 701, name: 'Puerto Gaitán', id_department: 50 },
    { id_city: 702, name: 'Puerto Guzmán', id_department: 86 },
    { id_city: 703, name: 'Puerto Leguízamo', id_department: 86 },
    { id_city: 704, name: 'Puerto Libertador', id_department: 23 },
    { id_city: 705, name: 'Puerto Lleras', id_department: 50 },
    { id_city: 706, name: 'Puerto López', id_department: 50 },
    { id_city: 707, name: 'Puerto Nare', id_department: 5 },
    { id_city: 708, name: 'Puerto Nariño', id_department: 91 },
    { id_city: 709, name: 'Puerto Parra', id_department: 68 },
    { id_city: 710, name: 'Puerto Rico', id_department: 18 },
    { id_city: 711, name: 'Puerto Rico', id_department: 50 },
    { id_city: 712, name: 'Puerto Rondón', id_department: 81 },
    { id_city: 713, name: 'Puerto Salgar', id_department: 25 },
    { id_city: 714, name: 'Puerto Santander', id_department: 54 },
    { id_city: 715, name: 'Puerto Tejada', id_department: 19 },
    { id_city: 716, name: 'Puerto Triunfo', id_department: 5 },
    { id_city: 717, name: 'Puerto Wilches', id_department: 68 },
    { id_city: 718, name: 'Pulí', id_department: 25 },
    { id_city: 719, name: 'Pupiales', id_department: 52 },
    { id_city: 720, name: 'Puracé (Coconuco)', id_department: 19 },
    { id_city: 721, name: 'Purificación', id_department: 73 },
    { id_city: 722, name: 'Purísima', id_department: 23 },
    { id_city: 723, name: 'Pácora', id_department: 17 },
    { id_city: 724, name: 'Páez', id_department: 15 },
    { id_city: 725, name: 'Páez (Belalcazar)', id_department: 19 },
    { id_city: 726, name: 'Páramo', id_department: 68 },
    { id_city: 727, name: 'Quebradanegra', id_department: 25 },
    { id_city: 728, name: 'Quetame', id_department: 25 },
    { id_city: 729, name: 'Quibdó', id_department: 27 },
    { id_city: 730, name: 'Quimbaya', id_department: 63 },
    { id_city: 731, name: 'Quinchía', id_department: 66 },
    { id_city: 732, name: 'Quipama', id_department: 15 },
    { id_city: 733, name: 'Quipile', id_department: 25 },
    { id_city: 734, name: 'Ragonvalia', id_department: 54 },
    { id_city: 735, name: 'Ramiriquí', id_department: 15 },
    { id_city: 736, name: 'Recetor', id_department: 85 },
    { id_city: 737, name: 'Regidor', id_department: 13 },
    { id_city: 738, name: 'Remedios', id_department: 5 },
    { id_city: 739, name: 'Remolino', id_department: 47 },
    { id_city: 740, name: 'Repelón', id_department: 8 },
    { id_city: 741, name: 'Restrepo', id_department: 50 },
    { id_city: 742, name: 'Restrepo', id_department: 76 },
    { id_city: 743, name: 'Retiro', id_department: 5 },
    { id_city: 744, name: 'Ricaurte', id_department: 25 },
    { id_city: 745, name: 'Ricaurte', id_department: 52 },
    { id_city: 746, name: 'Rio Negro', id_department: 68 },
    { id_city: 747, name: 'Rioblanco', id_department: 73 },
    { id_city: 748, name: 'Riofrío', id_department: 76 },
    { id_city: 749, name: 'Riohacha', id_department: 44 },
    { id_city: 750, name: 'Risaralda', id_department: 17 },
    { id_city: 751, name: 'Rivera', id_department: 41 },
    { id_city: 752, name: 'Roberto Payán (San José)', id_department: 52 },
    { id_city: 753, name: 'Roldanillo', id_department: 76 },
    { id_city: 754, name: 'Roncesvalles', id_department: 73 },
    { id_city: 755, name: 'Rondón', id_department: 15 },
    { id_city: 756, name: 'Rosas', id_department: 19 },
    { id_city: 757, name: 'Rovira', id_department: 73 },
    { id_city: 758, name: 'Ráquira', id_department: 15 },
    { id_city: 759, name: 'Río Iró', id_department: 27 },
    { id_city: 760, name: 'Río Quito', id_department: 27 },
    { id_city: 761, name: 'Río Sucio', id_department: 17 },
    { id_city: 762, name: 'Río Viejo', id_department: 13 },
    { id_city: 763, name: 'Río de oro', id_department: 20 },
    { id_city: 764, name: 'Ríonegro', id_department: 5 },
    { id_city: 765, name: 'Ríosucio', id_department: 27 },
    { id_city: 766, name: 'Sabana de Torres', id_department: 68 },
    { id_city: 767, name: 'Sabanagrande', id_department: 8 },
    { id_city: 768, name: 'Sabanalarga', id_department: 5 },
    { id_city: 769, name: 'Sabanalarga', id_department: 8 },
    { id_city: 770, name: 'Sabanalarga', id_department: 85 },
    { id_city: 771, name: 'Sabanas de San Angel (SAN ANGEL)', id_department: 47 },
    { id_city: 772, name: 'Sabaneta', id_department: 5 },
    { id_city: 773, name: 'Saboyá', id_department: 15 },
    { id_city: 774, name: 'Sahagún', id_department: 23 },
    { id_city: 775, name: 'Saladoblanco', id_department: 41 },
    { id_city: 776, name: 'Salamina', id_department: 17 },
    { id_city: 777, name: 'Salamina', id_department: 47 },
    { id_city: 778, name: 'Salazar', id_department: 54 },
    { id_city: 779, name: 'Saldaña', id_department: 73 },
    { id_city: 780, name: 'Salento', id_department: 63 },
    { id_city: 781, name: 'Salgar', id_department: 5 },
    { id_city: 782, name: 'Samacá', id_department: 15 },
    { id_city: 783, name: 'Samaniego', id_department: 52 },
    { id_city: 784, name: 'Samaná', id_department: 17 },
    { id_city: 785, name: 'Sampués', id_department: 70 },
    { id_city: 786, name: 'San Agustín', id_department: 41 },
    { id_city: 787, name: 'San Alberto', id_department: 20 },
    { id_city: 788, name: 'San Andrés', id_department: 68 },
    { id_city: 789, name: 'San Andrés Sotavento', id_department: 23 },
    { id_city: 790, name: 'San Andrés de Cuerquía', id_department: 5 },
    { id_city: 791, name: 'San Antero', id_department: 23 },
    { id_city: 792, name: 'San Antonio', id_department: 73 },
    { id_city: 793, name: 'San Antonio de Tequendama', id_department: 25 },
    { id_city: 794, name: 'San Benito', id_department: 68 },
    { id_city: 795, name: 'San Benito Abad', id_department: 70 },
    { id_city: 796, name: 'San Bernardo', id_department: 25 },
    { id_city: 797, name: 'San Bernardo', id_department: 52 },
    { id_city: 798, name: 'San Bernardo del Viento', id_department: 23 },
    { id_city: 799, name: 'San Calixto', id_department: 54 },
    { id_city: 800, name: 'San Carlos', id_department: 5 },
    { id_city: 801, name: 'San Carlos', id_department: 23 },
    { id_city: 802, name: 'San Carlos de Guaroa', id_department: 50 },
    { id_city: 803, name: 'San Cayetano', id_department: 25 },
    { id_city: 804, name: 'San Cayetano', id_department: 54 },
    { id_city: 805, name: 'San Cristobal', id_department: 13 },
    { id_city: 806, name: 'San Diego', id_department: 20 },
    { id_city: 807, name: 'San Eduardo', id_department: 15 },
    { id_city: 808, name: 'San Estanislao', id_department: 13 },
    { id_city: 809, name: 'San Fernando', id_department: 13 },
    { id_city: 810, name: 'San Francisco', id_department: 5 },
    { id_city: 811, name: 'San Francisco', id_department: 25 },
    { id_city: 812, name: 'San Francisco', id_department: 86 },
    { id_city: 813, name: 'San Gíl', id_department: 68 },
    { id_city: 814, name: 'San Jacinto', id_department: 13 },
    { id_city: 815, name: 'San Jacinto del Cauca', id_department: 13 },
    { id_city: 816, name: 'San Jerónimo', id_department: 5 },
    { id_city: 817, name: 'San Joaquín', id_department: 68 },
    { id_city: 818, name: 'San José', id_department: 17 },
    { id_city: 819, name: 'San José de Miranda', id_department: 68 },
    { id_city: 820, name: 'San José de Montaña', id_department: 5 },
    { id_city: 821, name: 'San José de Pare', id_department: 15 },
    { id_city: 822, name: 'San José de Uré', id_department: 23 },
    { id_city: 823, name: 'San José del Fragua', id_department: 18 },
    { id_city: 824, name: 'San José del Guaviare', id_department: 95 },
    { id_city: 825, name: 'San José del Palmar', id_department: 27 },
    { id_city: 826, name: 'San Juan de Arama', id_department: 50 },
    { id_city: 827, name: 'San Juan de Betulia', id_department: 70 },
    { id_city: 828, name: 'San Juan de Nepomuceno', id_department: 13 },
    { id_city: 829, name: 'San Juan de Pasto', id_department: 52 },
    { id_city: 830, name: 'San Juan de Río Seco', id_department: 25 },
    { id_city: 831, name: 'San Juan de Urabá', id_department: 5 },
    { id_city: 832, name: 'San Juan del Cesar', id_department: 44 },
    { id_city: 833, name: 'San Juanito', id_department: 50 },
    { id_city: 834, name: 'San Lorenzo', id_department: 52 },
    { id_city: 835, name: 'San Luis', id_department: 73 },
    { id_city: 836, name: 'San Luís', id_department: 5 },
    { id_city: 837, name: 'San Luís de Gaceno', id_department: 15 },
    { id_city: 838, name: 'San Luís de Palenque', id_department: 85 },
    { id_city: 839, name: 'San Marcos', id_department: 70 },
    { id_city: 840, name: 'San Martín', id_department: 20 },
    { id_city: 841, name: 'San Martín', id_department: 50 },
    { id_city: 842, name: 'San Martín de Loba', id_department: 13 },
    { id_city: 843, name: 'San Mateo', id_department: 15 },
    { id_city: 844, name: 'San Miguel', id_department: 68 },
    { id_city: 845, name: 'San Miguel', id_department: 86 },
    { id_city: 846, name: 'San Miguel de Sema', id_department: 15 },
    { id_city: 847, name: 'San Onofre', id_department: 70 },
    { id_city: 848, name: 'San Pablo', id_department: 13 },
    { id_city: 849, name: 'San Pablo', id_department: 52 },
    { id_city: 850, name: 'San Pablo de Borbur', id_department: 15 },
    { id_city: 851, name: 'San Pedro', id_department: 5 },
    { id_city: 852, name: 'San Pedro', id_department: 70 },
    { id_city: 853, name: 'San Pedro', id_department: 76 },
    { id_city: 854, name: 'San Pedro de Cartago', id_department: 52 },
    { id_city: 855, name: 'San Pedro de Urabá', id_department: 5 },
    { id_city: 856, name: 'San Pelayo', id_department: 23 },
    { id_city: 857, name: 'San Rafael', id_department: 5 },
    { id_city: 858, name: 'San Roque', id_department: 5 },
    { id_city: 859, name: 'San Sebastián', id_department: 19 },
    { id_city: 860, name: 'San Sebastián de Buenavista', id_department: 47 },
    { id_city: 861, name: 'San Vicente', id_department: 5 },
    { id_city: 862, name: 'San Vicente del Caguán', id_department: 18 },
    { id_city: 863, name: 'San Vicente del Chucurí', id_department: 68 },
    { id_city: 864, name: 'San Zenón', id_department: 47 },
    { id_city: 865, name: 'Sandoná', id_department: 52 },
    { id_city: 866, name: 'Santa Ana', id_department: 47 },
    { id_city: 867, name: 'Santa Bárbara', id_department: 5 },
    { id_city: 868, name: 'Santa Bárbara', id_department: 68 },
    { id_city: 869, name: 'Santa Bárbara (Iscuandé)', id_department: 52 },
    { id_city: 870, name: 'Santa Bárbara de Pinto', id_department: 47 },
    { id_city: 871, name: 'Santa Catalina', id_department: 13 },
    { id_city: 872, name: 'Santa Fé de Antioquia', id_department: 5 },
    { id_city: 873, name: 'Santa Genoveva de Docorodó', id_department: 27 },
    { id_city: 874, name: 'Santa Helena del Opón', id_department: 68 },
    { id_city: 875, name: 'Santa Isabel', id_department: 73 },
    { id_city: 876, name: 'Santa Lucía', id_department: 8 },
    { id_city: 877, name: 'Santa Marta', id_department: 47 },
    { id_city: 878, name: 'Santa María', id_department: 15 },
    { id_city: 879, name: 'Santa María', id_department: 41 },
    { id_city: 880, name: 'Santa Rosa', id_department: 13 },
    { id_city: 881, name: 'Santa Rosa', id_department: 19 },
    { id_city: 882, name: 'Santa Rosa de Cabal', id_department: 66 },
    { id_city: 883, name: 'Santa Rosa de Osos', id_department: 5 },
    { id_city: 884, name: 'Santa Rosa de Viterbo', id_department: 15 },
    { id_city: 885, name: 'Santa Rosa del Sur', id_department: 13 },
    { id_city: 886, name: 'Santa Rosalía', id_department: 99 },
    { id_city: 887, name: 'Santa Sofía', id_department: 15 },
    { id_city: 888, name: 'Santana', id_department: 15 },
    { id_city: 889, name: 'Santander de Quilichao', id_department: 19 },
    { id_city: 890, name: 'Santiago', id_department: 54 },
    { id_city: 891, name: 'Santiago', id_department: 86 },
    { id_city: 892, name: 'Santo Domingo', id_department: 5 },
    { id_city: 893, name: 'Santo Tomás', id_department: 8 },
    { id_city: 894, name: 'Santuario', id_department: 5 },
    { id_city: 895, name: 'Santuario', id_department: 66 },
    { id_city: 896, name: 'Sapuyes', id_department: 52 },
    { id_city: 897, name: 'Saravena', id_department: 81 },
    { id_city: 898, name: 'Sardinata', id_department: 54 },
    { id_city: 899, name: 'Sasaima', id_department: 25 },
    { id_city: 900, name: 'Sativanorte', id_department: 15 },
    { id_city: 901, name: 'Sativasur', id_department: 15 },
    { id_city: 902, name: 'Segovia', id_department: 5 },
    { id_city: 903, name: 'Sesquilé', id_department: 25 },
    { id_city: 904, name: 'Sevilla', id_department: 76 },
    { id_city: 905, name: 'Siachoque', id_department: 15 },
    { id_city: 906, name: 'Sibaté', id_department: 25 },
    { id_city: 907, name: 'Sibundoy', id_department: 86 },
    { id_city: 908, name: 'Silos', id_department: 54 },
    { id_city: 909, name: 'Silvania', id_department: 25 },
    { id_city: 910, name: 'Silvia', id_department: 19 },
    { id_city: 911, name: 'Simacota', id_department: 68 },
    { id_city: 912, name: 'Simijaca', id_department: 25 },
    { id_city: 913, name: 'Simití', id_department: 13 },
    { id_city: 914, name: 'Sincelejo', id_department: 70 },
    { id_city: 915, name: 'Sincé', id_department: 70 },
    { id_city: 916, name: 'Sipí', id_department: 27 },
    { id_city: 917, name: 'Sitionuevo', id_department: 47 },
    { id_city: 918, name: 'Soacha', id_department: 25 },
    { id_city: 919, name: 'Soatá', id_department: 15 },
    { id_city: 920, name: 'Socha', id_department: 15 },
    { id_city: 921, name: 'Socorro', id_department: 68 },
    { id_city: 922, name: 'Socotá', id_department: 15 },
    { id_city: 923, name: 'Sogamoso', id_department: 15 },
    { id_city: 924, name: 'Solano', id_department: 18 },
    { id_city: 925, name: 'Soledad', id_department: 8 },
    { id_city: 926, name: 'Solita', id_department: 18 },
    { id_city: 927, name: 'Somondoco', id_department: 15 },
    { id_city: 928, name: 'Sonsón', id_department: 5 },
    { id_city: 929, name: 'Sopetrán', id_department: 5 },
    { id_city: 930, name: 'Soplaviento', id_department: 13 },
    { id_city: 931, name: 'Sopó', id_department: 25 },
    { id_city: 932, name: 'Sora', id_department: 15 },
    { id_city: 933, name: 'Soracá', id_department: 15 },
    { id_city: 934, name: 'Sotaquirá', id_department: 15 },
    { id_city: 935, name: 'Sotara (Paispamba)', id_department: 19 },
    { id_city: 936, name: 'Sotomayor (Los Andes)', id_department: 52 },
    { id_city: 937, name: 'Suaita', id_department: 68 },
    { id_city: 938, name: 'Suan', id_department: 8 },
    { id_city: 939, name: 'Suaza', id_department: 41 },
    { id_city: 940, name: 'Subachoque', id_department: 25 },
    { id_city: 941, name: 'Sucre', id_department: 19 },
    { id_city: 942, name: 'Sucre', id_department: 68 },
    { id_city: 943, name: 'Sucre', id_department: 70 },
    { id_city: 944, name: 'Suesca', id_department: 25 },
    { id_city: 945, name: 'Supatá', id_department: 25 },
    { id_city: 946, name: 'Supía', id_department: 17 },
    { id_city: 947, name: 'Suratá', id_department: 68 },
    { id_city: 948, name: 'Susa', id_department: 25 },
    { id_city: 949, name: 'Susacón', id_department: 15 },
    { id_city: 950, name: 'Sutamarchán', id_department: 15 },
    { id_city: 951, name: 'Sutatausa', id_department: 25 },
    { id_city: 952, name: 'Sutatenza', id_department: 15 },
    { id_city: 953, name: 'Suárez', id_department: 19 },
    { id_city: 954, name: 'Suárez', id_department: 73 },
    { id_city: 955, name: 'Sácama', id_department: 85 },
    { id_city: 956, name: 'Sáchica', id_department: 15 },
    { id_city: 957, name: 'Tabio', id_department: 25 },
    { id_city: 958, name: 'Tadó', id_department: 27 },
    { id_city: 959, name: 'Talaigua Nuevo', id_department: 13 },
    { id_city: 960, name: 'Tamalameque', id_department: 20 },
    { id_city: 961, name: 'Tame', id_department: 81 },
    { id_city: 962, name: 'Taminango', id_department: 52 },
    { id_city: 963, name: 'Tangua', id_department: 52 },
    { id_city: 964, name: 'Taraira', id_department: 97 },
    { id_city: 965, name: 'Tarazá', id_department: 5 },
    { id_city: 966, name: 'Tarqui', id_department: 41 },
    { id_city: 967, name: 'Tarso', id_department: 5 },
    { id_city: 968, name: 'Tasco', id_department: 15 },
    { id_city: 969, name: 'Tauramena', id_department: 85 },
    { id_city: 970, name: 'Tausa', id_department: 25 },
    { id_city: 971, name: 'Tello', id_department: 41 },
    { id_city: 972, name: 'Tena', id_department: 25 },
    { id_city: 973, name: 'Tenerife', id_department: 47 },
    { id_city: 974, name: 'Tenjo', id_department: 25 },
    { id_city: 975, name: 'Tenza', id_department: 15 },
    { id_city: 976, name: 'Teorama', id_department: 54 },
    { id_city: 977, name: 'Teruel', id_department: 41 },
    { id_city: 978, name: 'Tesalia', id_department: 41 },
    { id_city: 979, name: 'Tibacuy', id_department: 25 },
    { id_city: 980, name: 'Tibaná', id_department: 15 },
    { id_city: 981, name: 'Tibasosa', id_department: 15 },
    { id_city: 982, name: 'Tibirita', id_department: 25 },
    { id_city: 983, name: 'Tibú', id_department: 54 },
    { id_city: 984, name: 'Tierralta', id_department: 23 },
    { id_city: 985, name: 'Timaná', id_department: 41 },
    { id_city: 986, name: 'Timbiquí', id_department: 19 },
    { id_city: 987, name: 'Timbío', id_department: 19 },
    { id_city: 988, name: 'Tinjacá', id_department: 15 },
    { id_city: 989, name: 'Tipacoque', id_department: 15 },
    { id_city: 990, name: 'Tiquisio (Puerto Rico)', id_department: 13 },
    { id_city: 991, name: 'Titiribí', id_department: 5 },
    { id_city: 992, name: 'Toca', id_department: 15 },
    { id_city: 993, name: 'Tocaima', id_department: 25 },
    { id_city: 994, name: 'Tocancipá', id_department: 25 },
    { id_city: 995, name: 'Toguí', id_department: 15 },
    { id_city: 996, name: 'Toledo', id_department: 5 },
    { id_city: 997, name: 'Toledo', id_department: 54 },
    { id_city: 998, name: 'Tolú', id_department: 70 },
    { id_city: 999, name: 'Tolú Viejo', id_department: 70 },
    { id_city: 1000, name: 'Tona', id_department: 68 },
    { id_city: 1001, name: 'Topagá', id_department: 15 },
    { id_city: 1002, name: 'Topaipí', id_department: 25 },
    { id_city: 1003, name: 'Toribío', id_department: 19 },
    { id_city: 1004, name: 'Toro', id_department: 76 },
    { id_city: 1005, name: 'Tota', id_department: 15 },
    { id_city: 1006, name: 'Totoró', id_department: 19 },
    { id_city: 1007, name: 'Trinidad', id_department: 85 },
    { id_city: 1008, name: 'Trujillo', id_department: 76 },
    { id_city: 1009, name: 'Tubará', id_department: 8 },
    { id_city: 1010, name: 'Tuchín', id_department: 23 },
    { id_city: 1011, name: 'Tulúa', id_department: 76 },
    { id_city: 1012, name: 'Tumaco', id_department: 52 },
    { id_city: 1013, name: 'Tunja', id_department: 15 },
    { id_city: 1014, name: 'Tunungua', id_department: 15 },
    { id_city: 1015, name: 'Turbaco', id_department: 13 },
    { id_city: 1016, name: 'Turbaná', id_department: 13 },
    { id_city: 1017, name: 'Turbo', id_department: 5 },
    { id_city: 1018, name: 'Turmequé', id_department: 15 },
    { id_city: 1019, name: 'Tuta', id_department: 15 },
    { id_city: 1020, name: 'Tutasá', id_department: 15 },
    { id_city: 1021, name: 'Támara', id_department: 85 },
    { id_city: 1022, name: 'Támesis', id_department: 5 },
    { id_city: 1023, name: 'Túquerres', id_department: 52 },
    { id_city: 1024, name: 'Ubalá', id_department: 25 },
    { id_city: 1025, name: 'Ubaque', id_department: 25 },
    { id_city: 1026, name: 'Ubaté', id_department: 25 },
    { id_city: 1027, name: 'Ulloa', id_department: 76 },
    { id_city: 1028, name: 'Une', id_department: 25 },
    { id_city: 1029, name: 'Unguía', id_department: 27 },
    { id_city: 1030, name: 'Unión Panamericana (ÁNIMAS)', id_department: 27 },
    { id_city: 1031, name: 'Uramita', id_department: 5 },
    { id_city: 1032, name: 'Uribe', id_department: 50 },
    { id_city: 1033, name: 'Uribia', id_department: 44 },
    { id_city: 1034, name: 'Urrao', id_department: 5 },
    { id_city: 1035, name: 'Urumita', id_department: 44 },
    { id_city: 1036, name: 'Usiacuri', id_department: 8 },
    { id_city: 1037, name: 'Valdivia', id_department: 5 },
    { id_city: 1038, name: 'Valencia', id_department: 23 },
    { id_city: 1039, name: 'Valle de San José', id_department: 68 },
    { id_city: 1040, name: 'Valle de San Juan', id_department: 73 },
    { id_city: 1041, name: 'Valle del Guamuez', id_department: 86 },
    { id_city: 1042, name: 'Valledupar', id_department: 20 },
    { id_city: 1043, name: 'Valparaiso', id_department: 5 },
    { id_city: 1044, name: 'Valparaiso', id_department: 18 },
    { id_city: 1045, name: 'Vegachí', id_department: 5 },
    { id_city: 1046, name: 'Venadillo', id_department: 73 },
    { id_city: 1047, name: 'Venecia', id_department: 5 },
    { id_city: 1048, name: 'Venecia (Ospina Pérez)', id_department: 25 },
    { id_city: 1049, name: 'Ventaquemada', id_department: 15 },
    { id_city: 1050, name: 'Vergara', id_department: 25 },
    { id_city: 1051, name: 'Versalles', id_department: 76 },
    { id_city: 1052, name: 'Vetas', id_department: 68 },
    { id_city: 1053, name: 'Viani', id_department: 25 },
    { id_city: 1054, name: 'Vigía del Fuerte', id_department: 5 },
    { id_city: 1055, name: 'Vijes', id_department: 76 },
    { id_city: 1056, name: 'Villa Caro', id_department: 54 },
    { id_city: 1057, name: 'Villa Rica', id_department: 19 },
    { id_city: 1058, name: 'Villa de Leiva', id_department: 15 },
    { id_city: 1059, name: 'Villa del Rosario', id_department: 54 },
    { id_city: 1060, name: 'Villagarzón', id_department: 86 },
    { id_city: 1061, name: 'Villagómez', id_department: 25 },
    { id_city: 1062, name: 'Villahermosa', id_department: 73 },
    { id_city: 1063, name: 'Villamaría', id_department: 17 },
    { id_city: 1064, name: 'Villanueva', id_department: 13 },
    { id_city: 1065, name: 'Villanueva', id_department: 44 },
    { id_city: 1066, name: 'Villanueva', id_department: 68 },
    { id_city: 1067, name: 'Villanueva', id_department: 85 },
    { id_city: 1068, name: 'Villapinzón', id_department: 25 },
    { id_city: 1069, name: 'Villarrica', id_department: 73 },
    { id_city: 1070, name: 'Villavicencio', id_department: 50 },
    { id_city: 1071, name: 'Villavieja', id_department: 41 },
    { id_city: 1072, name: 'Villeta', id_department: 25 },
    { id_city: 1073, name: 'Viotá', id_department: 25 },
    { id_city: 1074, name: 'Viracachá', id_department: 15 },
    { id_city: 1075, name: 'Vista Hermosa', id_department: 50 },
    { id_city: 1076, name: 'Viterbo', id_department: 17 },
    { id_city: 1077, name: 'Vélez', id_department: 68 },
    { id_city: 1078, name: 'Yacopí', id_department: 25 },
    { id_city: 1079, name: 'Yacuanquer', id_department: 52 },
    { id_city: 1080, name: 'Yaguará', id_department: 41 },
    { id_city: 1081, name: 'Yalí', id_department: 5 },
    { id_city: 1082, name: 'Yarumal', id_department: 5 },
    { id_city: 1083, name: 'Yolombó', id_department: 5 },
    { id_city: 1084, name: 'Yondó (Casabe)', id_department: 5 },
    { id_city: 1085, name: 'Yopal', id_department: 85 },
    { id_city: 1086, name: 'Yotoco', id_department: 76 },
    { id_city: 1087, name: 'Yumbo', id_department: 76 },
    { id_city: 1088, name: 'Zambrano', id_department: 13 },
    { id_city: 1089, name: 'Zapatoca', id_department: 68 },
    { id_city: 1090, name: 'Zapayán (PUNTA DE PIEDRAS)', id_department: 47 },
    { id_city: 1091, name: 'Zaragoza', id_department: 5 },
    { id_city: 1092, name: 'Zarzal', id_department: 76 },
    { id_city: 1093, name: 'Zetaquirá', id_department: 15 },
    { id_city: 1094, name: 'Zipacón', id_department: 25 },
    { id_city: 1095, name: 'Zipaquirá', id_department: 25 },
    { id_city: 1096, name: 'Zona Bananera (PRADO - SEVILLA)', id_department: 47 },
    { id_city: 1097, name: 'Ábrego', id_department: 54 },
    { id_city: 1098, name: 'Íquira', id_department: 41 },
    { id_city: 1099, name: 'Úmbita', id_department: 15 },
    { id_city: 1100, name: 'Útica', id_department: 25 }
  ]

  const role = [
    { id_rol: 1, name: 'Admin' },
    { id_rol: 2, name: 'Client' }
  ]

  const salesStatus = [
    { id_status: 1, name: 'Cotización', descriptionClient: 'hola', descriptionAdmin: 'da' },
    { id_status: 2, name: 'Para Pagar', descriptionClient: 'fds', descriptionAdmin: 'da' },
    { id_status: 3, name: 'Producción', descriptionClient: 'sdf', descriptionAdmin: 'da' },
    { id_status: 4, name: 'Enviado', descriptionClient: 'sdf', descriptionAdmin: 'da' },
    { id_status: 5, name: 'Entregado', descriptionClient: 'sdf', descriptionAdmin: 'da' },
    { id_status: 6, name: 'Cancelado', descriptionClient: 'sdf', descriptionAdmin: 'da' }
  ]

  // ? Insertar datos de tipos de documentos
  await prisma.salesStatus.createMany({
    data: salesStatus.map((status) => ({
      id_status: status.id_status,
      name: status.name,
      descriptionClient: status.descriptionClient,
      descriptionAdmin: status.descriptionAdmin
    }))
  })

  // ? Insertar datos de tipos de documentos
  await prisma.documentType.createMany({
    data: tiposDeDocumentos.map((tipo) => ({
      id_document_type: tipo.id_document_type,
      name: tipo.name,
      description: tipo.description
    }))
  })

  // ? Insertar datos de tipos de documentos
  await prisma.Country.createMany({
    data: Paises.map((pais) => ({
      id_country: pais.id_country,
      name: pais.name,
      currency: pais.currency,
      locale: pais.locale
    }))
  })

  // ? Insertar departamentos en la base de datos
  await prisma.department.createMany({
    data: departamentos.map((departamento) => ({
      id_department: departamento.id_department,
      name: departamento.name,
      id_country: departamento.id_country
    }))
  })

  // ? Insertar ciudades (municipios) en la base de datos
  await prisma.city.createMany({
    data: municipios.map((municipio) => ({
      id_city: municipio.id_city,
      name: municipio.name,
      id_department: municipio.id_department
    }))
  })

  await prisma.roles.createMany({
    data: role.map((rol) => ({
      id_rol: rol.id_rol,
      name: rol.name
    }))
  })

  // ? Users de prueba
  await prisma.Users.createMany({
    data: usuarios.map((user) => ({
      document_type: user.document_type,
      document: user.document,
      name: user.name,
      avatar: user.avatar,
      campo: user.campo,
      id_country: user.id_country,
      id_department: user.id_department,
      id_city: user.id_city,
      address: user.address,
      phone: user.phone,
      email: user.email,
      password: user.password,
      id_rol: user.id_rol
    }))
  })

  console.log('Seeds creados exitosamente... 😎👍👌')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
