import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {

  //? Lista de departamentos
  const departamentos = [
    { departmentID: 5, nombre: 'ANTIOQUIA' },
    { departmentID: 8, nombre: 'ATLÁNTICO' },
    { departmentID: 11, nombre: 'BOGOTÁ, D.C.' },
    { departmentID: 13, nombre: 'BOLÍVAR' },
    { departmentID: 15, nombre: 'BOYACÁ' },
    { departmentID: 17, nombre: 'CALDAS' },
    { departmentID: 18, nombre: 'CAQUETÁ' },
    { departmentID: 19, nombre: 'CAUCA' },
    { departmentID: 20, nombre: 'CESAR' },
    { departmentID: 23, nombre: 'CÓRDOBA' },
    { departmentID: 25, nombre: 'CUNDINAMARCA' },
    { departmentID: 27, nombre: 'CHOCÓ' },
    { departmentID: 41, nombre: 'HUILA' },
    { departmentID: 44, nombre: 'LA GUAJIRA' },
    { departmentID: 47, nombre: 'MAGDALENA' },
    { departmentID: 50, nombre: 'META' },
    { departmentID: 52, nombre: 'NARIÑO' },
    { departmentID: 54, nombre: 'NORTE DE SANTANDER' },
    { departmentID: 63, nombre: 'QUINDÍO' },
    { departmentID: 66, nombre: 'RISARALDA' },
    { departmentID: 68, nombre: 'SANTANDER' },
    { departmentID: 70, nombre: 'SUCRE' },
    { departmentID: 73, nombre: 'TOLIMA' },
    { departmentID: 76, nombre: 'VALLE DEL CAUCA' },
    { departmentID: 81, nombre: 'ARAUCA' },
    { departmentID: 85, nombre: 'CASANARE' },
    { departmentID: 86, nombre: 'PUTUMAYO' },
    { departmentID: 88, nombre: 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA' },
    { departmentID: 91, nombre: 'AMAZONAS' },
    { departmentID: 94, nombre: 'GUAINÍA' },
    { departmentID: 95, nombre: 'GUAVIARE' },
    { departmentID: 97, nombre: 'VAUPÉS' },
    { departmentID: 99, nombre: 'VICHADA' },
  ];

  //?listado de municipios
  const municipios =[
    {municipioID:1, nombre:'Abriaquí', departmentID:5},
    {municipioID:2, nombre:'Acacías', departmentID:50},
    {municipioID:3, nombre:'Acandí', departmentID:27},
    {municipioID:4, nombre:'Acevedo', departmentID:41},
    {municipioID:5, nombre:'Achí', departmentID:13},
    {municipioID:6, nombre:'Agrado', departmentID:41},
    {municipioID:7, nombre:'Agua de Dios', departmentID:25},
    {municipioID:8, nombre:'Aguachica', departmentID:20},
    {municipioID:9, nombre:'Aguada', departmentID:68},
    {municipioID:10, nombre:'Aguadas', departmentID:17},
    {municipioID:11, nombre:'Aguazul', departmentID:85},
    {municipioID:12, nombre:'Agustín Codazzi', departmentID:20},
    {municipioID:13, nombre:'Aipe', departmentID:41},
    {municipioID:14, nombre:'Albania', departmentID:18},
    {municipioID:15, nombre:'Albania', departmentID:44},
    {municipioID:16, nombre:'Albania', departmentID:68},
    {municipioID:17, nombre:'Albán', departmentID:25},
    {municipioID:18, nombre:'Albán (San José)', departmentID:52},
    {municipioID:19, nombre:'Alcalá', departmentID:76},
    {municipioID:20, nombre:'Alejandria', departmentID:5},
    {municipioID:21, nombre:'Algarrobo', departmentID:47},
    {municipioID:22, nombre:'Algeciras', departmentID:41},
    {municipioID:23, nombre:'Almaguer', departmentID:19},
    {municipioID:24, nombre:'Almeida', departmentID:15},
    {municipioID:25, nombre:'Alpujarra', departmentID:73},
    {municipioID:26, nombre:'Altamira', departmentID:41},
    {municipioID:27, nombre:'Alto Baudó (Pie de Pato)', departmentID:27},
    {municipioID:28, nombre:'Altos del Rosario', departmentID:13},
    {municipioID:29, nombre:'Alvarado', departmentID:73},
    {municipioID:30, nombre:'Amagá', departmentID:5},
    {municipioID:31, nombre:'Amalfi', departmentID:5},
    {municipioID:32, nombre:'Ambalema', departmentID:73},
    {municipioID:33, nombre:'Anapoima', departmentID:25},
    {municipioID:34, nombre:'Ancuya', departmentID:52},
    {municipioID:35, nombre:'Andalucía', departmentID:76},
    {municipioID:36, nombre:'Andes', departmentID:5},
    {municipioID:37, nombre:'Angelópolis', departmentID:5},
    {municipioID:38, nombre:'Angostura', departmentID:5},
    {municipioID:39, nombre:'Anolaima', departmentID:25},
    {municipioID:40, nombre:'Anorí', departmentID:5},
    {municipioID:41, nombre:'Anserma', departmentID:17},
    {municipioID:42, nombre:'Ansermanuevo', departmentID:76},
    {municipioID:43, nombre:'Anzoátegui', departmentID:73},
    {municipioID:44, nombre:'Anzá', departmentID:5},
    {municipioID:45, nombre:'Apartadó', departmentID:5},
    {municipioID:46, nombre:'Apulo', departmentID:25},
    {municipioID:47, nombre:'Apía', departmentID:66},
    {municipioID:48, nombre:'Aquitania', departmentID:15},
    {municipioID:49, nombre:'Aracataca', departmentID:47},
    {municipioID:50, nombre:'Aranzazu', departmentID:17},
    {municipioID:51, nombre:'Aratoca', departmentID:68},
    {municipioID:52, nombre:'Arauca', departmentID:81},
    {municipioID:53, nombre:'Arauquita', departmentID:81},
    {municipioID:54, nombre:'Arbeláez', departmentID:25},
    {municipioID:55, nombre:'Arboleda (Berruecos)', departmentID:52},
    {municipioID:56, nombre:'Arboledas', departmentID:54},
    {municipioID:57, nombre:'Arboletes', departmentID:5},
    {municipioID:58, nombre:'Arcabuco', departmentID:15},
    {municipioID:59, nombre:'Arenal', departmentID:13},
    {municipioID:60, nombre:'Argelia', departmentID:5},
    {municipioID:61, nombre:'Argelia', departmentID:19},
    {municipioID:62, nombre:'Argelia', departmentID:76},
    {municipioID:63, nombre:'Ariguaní (El Difícil)', departmentID:47},
    {municipioID:64, nombre:'Arjona', departmentID:13},
    {municipioID:65, nombre:'Armenia', departmentID:5},
    {municipioID:66, nombre:'Armenia', departmentID:63},
    {municipioID:67, nombre:'Armero (Guayabal)', departmentID:73},
    {municipioID:68, nombre:'Arroyohondo', departmentID:13},
    {municipioID:69, nombre:'Astrea', departmentID:20},
    {municipioID:70, nombre:'Ataco', departmentID:73},
    {municipioID:71, nombre:'Atrato (Yuto)', departmentID:27},
    {municipioID:72, nombre:'Ayapel', departmentID:23},
    {municipioID:73, nombre:'Bagadó', departmentID:27},
    {municipioID:74, nombre:'Bahía Solano (Mútis)', departmentID:27},
    {municipioID:75, nombre:'Bajo Baudó (Pizarro)', departmentID:27},
    {municipioID:76, nombre:'Balboa', departmentID:19},
    {municipioID:77, nombre:'Balboa', departmentID:66},
    {municipioID:78, nombre:'Baranoa', departmentID:8},
    {municipioID:79, nombre:'Baraya', departmentID:41},
    {municipioID:80, nombre:'Barbacoas', departmentID:52},
    {municipioID:81, nombre:'Barbosa', departmentID:5},
    {municipioID:82, nombre:'Barbosa', departmentID:68},
    {municipioID:83, nombre:'Barichara', departmentID:68},
    {municipioID:84, nombre:'Barranca de Upía', departmentID:50},
    {municipioID:85, nombre:'Barrancabermeja', departmentID:68},
    {municipioID:86, nombre:'Barrancas', departmentID:44},
    {municipioID:87, nombre:'Barranco de Loba', departmentID:13},
    {municipioID:88, nombre:'Barranquilla', departmentID:8},
    {municipioID:89, nombre:'Becerríl', departmentID:20},
    {municipioID:90, nombre:'Belalcázar', departmentID:17},
    {municipioID:91, nombre:'Bello', departmentID:5},
    {municipioID:92, nombre:'Belmira', departmentID:5},
    {municipioID:93, nombre:'Beltrán', departmentID:25},
    {municipioID:94, nombre:'Belén', departmentID:15},
    {municipioID:95, nombre:'Belén', departmentID:52},
    {municipioID:96, nombre:'Belén de Bajirá', departmentID:27},
    {municipioID:97, nombre:'Belén de Umbría', departmentID:66},
    {municipioID:98, nombre:'Belén de los Andaquíes', departmentID:18},
    {municipioID:99, nombre:'Berbeo', departmentID:15},
    {municipioID:100, nombre:'Betania', departmentID:5},
    {municipioID:101, nombre:'Beteitiva', departmentID:15},
    {municipioID:102, nombre:'Betulia', departmentID:5},
    {municipioID:103, nombre:'Betulia', departmentID:68},
    {municipioID:104, nombre:'Bituima', departmentID:25},
    {municipioID:105, nombre:'Boavita', departmentID:15},
    {municipioID:106, nombre:'Bochalema', departmentID:54},
    {municipioID:107, nombre:'Bogotá D.C.', departmentID:11},
    {municipioID:108, nombre:'Bojacá', departmentID:25},
    {municipioID:109, nombre:'Bojayá (Bellavista)', departmentID:27},
    {municipioID:110, nombre:'Bolívar', departmentID:5},
    {municipioID:111, nombre:'Bolívar', departmentID:19},
    {municipioID:112, nombre:'Bolívar', departmentID:68},
    {municipioID:113, nombre:'Bolívar', departmentID:76},
    {municipioID:114, nombre:'Bosconia', departmentID:20},
    {municipioID:115, nombre:'Boyacá', departmentID:15},
    {municipioID:116, nombre:'Briceño', departmentID:5},
    {municipioID:117, nombre:'Briceño', departmentID:15},
    {municipioID:118, nombre:'Bucaramanga', departmentID:68},
    {municipioID:119, nombre:'Bucarasica', departmentID:54},
    {municipioID:120, nombre:'Buenaventura', departmentID:76},
    {municipioID:121, nombre:'Buenavista', departmentID:15},
    {municipioID:122, nombre:'Buenavista', departmentID:23},
    {municipioID:123, nombre:'Buenavista', departmentID:63},
    {municipioID:124, nombre:'Buenavista', departmentID:70},
    {municipioID:125, nombre:'Buenos Aires', departmentID:19},
    {municipioID:126, nombre:'Buesaco', departmentID:52},
    {municipioID:127, nombre:'Buga', departmentID:76},
    {municipioID:128, nombre:'Bugalagrande', departmentID:76},
    {municipioID:129, nombre:'Burítica', departmentID:5},
    {municipioID:130, nombre:'Busbanza', departmentID:15},
    {municipioID:131, nombre:'Cabrera', departmentID:25},
    {municipioID:132, nombre:'Cabrera', departmentID:68},
    {municipioID:133, nombre:'Cabuyaro', departmentID:50},
    {municipioID:134, nombre:'Cachipay', departmentID:25},
    {municipioID:135, nombre:'Caicedo', departmentID:5},
    {municipioID:136, nombre:'Caicedonia', departmentID:76},
    {municipioID:137, nombre:'Caimito', departmentID:70},
    {municipioID:138, nombre:'Cajamarca', departmentID:73},
    {municipioID:139, nombre:'Cajibío', departmentID:19},
    {municipioID:140, nombre:'Cajicá', departmentID:25},
    {municipioID:141, nombre:'Calamar', departmentID:13},
    {municipioID:142, nombre:'Calamar', departmentID:95},
    {municipioID:143, nombre:'Calarcá', departmentID:63},
    {municipioID:144, nombre:'Caldas', departmentID:5},
    {municipioID:145, nombre:'Caldas', departmentID:15},
    {municipioID:146, nombre:'Caldono', departmentID:19},
    {municipioID:147, nombre:'California', departmentID:68},
    {municipioID:148, nombre:'Calima (Darién)', departmentID:76},
    {municipioID:149, nombre:'Caloto', departmentID:19},
    {municipioID:150, nombre:'Calí', departmentID:76},
    {municipioID:151, nombre:'Campamento', departmentID:5},
    {municipioID:152, nombre:'Campo de la Cruz', departmentID:8},
    {municipioID:153, nombre:'Campoalegre', departmentID:41},
    {municipioID:154, nombre:'Campohermoso', departmentID:15},
    {municipioID:155, nombre:'Canalete', departmentID:23},
    {municipioID:156, nombre:'Candelaria', departmentID:8},
    {municipioID:157, nombre:'Candelaria', departmentID:76},
    {municipioID:158, nombre:'Cantagallo', departmentID:13},
    {municipioID:159, nombre:'Cantón de San Pablo', departmentID:27},
    {municipioID:160, nombre:'Caparrapí', departmentID:25},
    {municipioID:161, nombre:'Capitanejo', departmentID:68},
    {municipioID:162, nombre:'Caracolí', departmentID:5},
    {municipioID:163, nombre:'Caramanta', departmentID:5},
    {municipioID:164, nombre:'Carcasí', departmentID:68},
    {municipioID:165, nombre:'Carepa', departmentID:5},
    {municipioID:166, nombre:'Carmen de Apicalá', departmentID:73},
    {municipioID:167, nombre:'Carmen de Carupa', departmentID:25},
    {municipioID:168, nombre:'Carmen de Viboral', departmentID:5},
    {municipioID:169, nombre:'Carmen del Darién (CURBARADÓ)', departmentID:27},
    {municipioID:170, nombre:'Carolina', departmentID:5},
    {municipioID:171, nombre:'Cartagena', departmentID:13},
    {municipioID:172, nombre:'Cartagena del Chairá', departmentID:18},
    {municipioID:173, nombre:'Cartago', departmentID:76},
    {municipioID:174, nombre:'Carurú', departmentID:97},
    {municipioID:175, nombre:'Casabianca', departmentID:73},
    {municipioID:176, nombre:'Castilla la Nueva', departmentID:50},
    {municipioID:177, nombre:'Caucasia', departmentID:5},
    {municipioID:178, nombre:'Cañasgordas', departmentID:5},
    {municipioID:179, nombre:'Cepita', departmentID:68},
    {municipioID:180, nombre:'Cereté', departmentID:23},
    {municipioID:181, nombre:'Cerinza', departmentID:15},
    {municipioID:182, nombre:'Cerrito', departmentID:68},
    {municipioID:183, nombre:'Cerro San Antonio', departmentID:47},
    {municipioID:184, nombre:'Chachaguí', departmentID:52},
    {municipioID:185, nombre:'Chaguaní', departmentID:25},
    {municipioID:186, nombre:'Chalán', departmentID:70},
    {municipioID:187, nombre:'Chaparral', departmentID:73},
    {municipioID:188, nombre:'Charalá', departmentID:68},
    {municipioID:189, nombre:'Charta', departmentID:68},
    {municipioID:190, nombre:'Chigorodó', departmentID:5},
    {municipioID:191, nombre:'Chima', departmentID:68},
    {municipioID:192, nombre:'Chimichagua', departmentID:20},
    {municipioID:193, nombre:'Chimá', departmentID:23},
    {municipioID:194, nombre:'Chinavita', departmentID:15},
    {municipioID:195, nombre:'Chinchiná', departmentID:17},
    {municipioID:196, nombre:'Chinácota', departmentID:54},
    {municipioID:197, nombre:'Chinú', departmentID:23},
    {municipioID:198, nombre:'Chipaque', departmentID:25},
    {municipioID:199, nombre:'Chipatá', departmentID:68},
    {municipioID:200, nombre:'Chiquinquirá', departmentID:15},
    {municipioID:201, nombre:'Chiriguaná', departmentID:20},
    {municipioID:202, nombre:'Chiscas', departmentID:15},
    {municipioID:203, nombre:'Chita', departmentID:15},
    {municipioID:204, nombre:'Chitagá', departmentID:54},
    {municipioID:205, nombre:'Chitaraque', departmentID:15},
    {municipioID:206, nombre:'Chivatá', departmentID:15},
    {municipioID:207, nombre:'Chivolo', departmentID:47},
    {municipioID:208, nombre:'Choachí', departmentID:25},
    {municipioID:209, nombre:'Chocontá', departmentID:25},
    {municipioID:210, nombre:'Chámeza', departmentID:85},
    {municipioID:211, nombre:'Chía', departmentID:25},
    {municipioID:212, nombre:'Chíquiza', departmentID:15},
    {municipioID:213, nombre:'Chívor', departmentID:15},
    {municipioID:214, nombre:'Cicuco', departmentID:13},
    {municipioID:215, nombre:'Cimitarra', departmentID:68},
    {municipioID:216, nombre:'Circasia', departmentID:63},
    {municipioID:217, nombre:'Cisneros', departmentID:5},
    {municipioID:218, nombre:'Ciénaga', departmentID:15},
    {municipioID:219, nombre:'Ciénaga', departmentID:47},
    {municipioID:220, nombre:'Ciénaga de Oro', departmentID:23},
    {municipioID:221, nombre:'Clemencia', departmentID:13},
    {municipioID:222, nombre:'Cocorná', departmentID:5},
    {municipioID:223, nombre:'Coello', departmentID:73},
    {municipioID:224, nombre:'Cogua', departmentID:25},
    {municipioID:225, nombre:'Colombia', departmentID:41},
    {municipioID:226, nombre:'Colosó (Ricaurte)', departmentID:70},
    {municipioID:227, nombre:'Colón', departmentID:86},
    {municipioID:228, nombre:'Colón (Génova)', departmentID:52},
    {municipioID:229, nombre:'Concepción', departmentID:5},
    {municipioID:230, nombre:'Concepción', departmentID:68},
    {municipioID:231, nombre:'Concordia', departmentID:5},
    {municipioID:232, nombre:'Concordia', departmentID:47},
    {municipioID:233, nombre:'Condoto', departmentID:27},
    {municipioID:234, nombre:'Confines', departmentID:68},
    {municipioID:235, nombre:'Consaca', departmentID:52},
    {municipioID:236, nombre:'Contadero', departmentID:52},
    {municipioID:237, nombre:'Contratación', departmentID:68},
    {municipioID:238, nombre:'Convención', departmentID:54},
    {municipioID:239, nombre:'Copacabana', departmentID:5},
    {municipioID:240, nombre:'Coper', departmentID:15},
    {municipioID:241, nombre:'Cordobá', departmentID:63},
    {municipioID:242, nombre:'Corinto', departmentID:19},
    {municipioID:243, nombre:'Coromoro', departmentID:68},
    {municipioID:244, nombre:'Corozal', departmentID:70},
    {municipioID:245, nombre:'Corrales', departmentID:15},
    {municipioID:246, nombre:'Cota', departmentID:25},
    {municipioID:247, nombre:'Cotorra', departmentID:23},
    {municipioID:248, nombre:'Covarachía', departmentID:15},
    {municipioID:249, nombre:'Coveñas', departmentID:70},
    {municipioID:250, nombre:'Coyaima', departmentID:73},
    {municipioID:251, nombre:'Cravo Norte', departmentID:81},
    {municipioID:252, nombre:'Cuaspud (Carlosama)', departmentID:52},
    {municipioID:253, nombre:'Cubarral', departmentID:50},
    {municipioID:254, nombre:'Cubará', departmentID:15},
    {municipioID:255, nombre:'Cucaita', departmentID:15},
    {municipioID:256, nombre:'Cucunubá', departmentID:25},
    {municipioID:257, nombre:'Cucutilla', departmentID:54},
    {municipioID:258, nombre:'Cuitiva', departmentID:15},
    {municipioID:259, nombre:'Cumaral', departmentID:50},
    {municipioID:260, nombre:'Cumaribo', departmentID:99},
    {municipioID:261, nombre:'Cumbal', departmentID:52},
    {municipioID:262, nombre:'Cumbitara', departmentID:52},
    {municipioID:263, nombre:'Cunday', departmentID:73},
    {municipioID:264, nombre:'Curillo', departmentID:18},
    {municipioID:265, nombre:'Curití', departmentID:68},
    {municipioID:266, nombre:'Curumaní', departmentID:20},
    {municipioID:267, nombre:'Cáceres', departmentID:5},
    {municipioID:268, nombre:'Cáchira', departmentID:54},
    {municipioID:269, nombre:'Cácota', departmentID:54},
    {municipioID:270, nombre:'Cáqueza', departmentID:25},
    {municipioID:271, nombre:'Cértegui', departmentID:27},
    {municipioID:272, nombre:'Cómbita', departmentID:15},
    {municipioID:273, nombre:'Córdoba', departmentID:13},
    {municipioID:274, nombre:'Córdoba', departmentID:52},
    {municipioID:275, nombre:'Cúcuta', departmentID:54},
    {municipioID:276, nombre:'Dabeiba', departmentID:5},
    {municipioID:277, nombre:'Dagua', departmentID:76},
    {municipioID:278, nombre:'Dibulla', departmentID:44},
    {municipioID:279, nombre:'Distracción', departmentID:44},
    {municipioID:280, nombre:'Dolores', departmentID:73},
    {municipioID:281, nombre:'Don Matías', departmentID:5},
    {municipioID:282, nombre:'Dos Quebradas', departmentID:66},
    {municipioID:283, nombre:'Duitama', departmentID:15},
    {municipioID:284, nombre:'Durania', departmentID:54},
    {municipioID:285, nombre:'Ebéjico', departmentID:5},
    {municipioID:286, nombre:'El Bagre', departmentID:5},
    {municipioID:287, nombre:'El Banco', departmentID:47},
    {municipioID:288, nombre:'El Cairo', departmentID:76},
    {municipioID:289, nombre:'El Calvario', departmentID:50},
    {municipioID:290, nombre:'El Carmen', departmentID:54},
    {municipioID:291, nombre:'El Carmen', departmentID:68},
    {municipioID:292, nombre:'El Carmen de Atrato', departmentID:27},
    {municipioID:293, nombre:'El Carmen de Bolívar', departmentID:13},
    {municipioID:294, nombre:'El Castillo', departmentID:50},
    {municipioID:295, nombre:'El Cerrito', departmentID:76},
    {municipioID:296, nombre:'El Charco', departmentID:52},
    {municipioID:297, nombre:'El Cocuy', departmentID:15},
    {municipioID:298, nombre:'El Colegio', departmentID:25},
    {municipioID:299, nombre:'El Copey', departmentID:20},
    {municipioID:300, nombre:'El Doncello', departmentID:18},
    {municipioID:301, nombre:'El Dorado', departmentID:50},
    {municipioID:302, nombre:'El Dovio', departmentID:76},
    {municipioID:303, nombre:'El Espino', departmentID:15},
    {municipioID:304, nombre:'El Guacamayo', departmentID:68},
    {municipioID:305, nombre:'El Guamo', departmentID:13},
    {municipioID:306, nombre:'El Molino', departmentID:44},
    {municipioID:307, nombre:'El Paso', departmentID:20},
    {municipioID:308, nombre:'El Paujil', departmentID:18},
    {municipioID:309, nombre:'El Peñol', departmentID:52},
    {municipioID:310, nombre:'El Peñon', departmentID:13},
    {municipioID:311, nombre:'El Peñon', departmentID:68},
    {municipioID:312, nombre:'El Peñón', departmentID:25},
    {municipioID:313, nombre:'El Piñon', departmentID:47},
    {municipioID:314, nombre:'El Playón', departmentID:68},
    {municipioID:315, nombre:'El Retorno', departmentID:95},
    {municipioID:316, nombre:'El Retén', departmentID:47},
    {municipioID:317, nombre:'El Roble', departmentID:70},
    {municipioID:318, nombre:'El Rosal', departmentID:25},
    {municipioID:319, nombre:'El Rosario', departmentID:52},
    {municipioID:320, nombre:'El Tablón de Gómez', departmentID:52},
    {municipioID:321, nombre:'El Tambo', departmentID:19},
    {municipioID:322, nombre:'El Tambo', departmentID:52},
    {municipioID:323, nombre:'El Tarra', departmentID:54},
    {municipioID:324, nombre:'El Zulia', departmentID:54},
    {municipioID:325, nombre:'El Águila', departmentID:76},
    {municipioID:326, nombre:'Elías', departmentID:41},
    {municipioID:327, nombre:'Encino', departmentID:68},
    {municipioID:328, nombre:'Enciso', departmentID:68},
    {municipioID:329, nombre:'Entrerríos', departmentID:5},
    {municipioID:330, nombre:'Envigado', departmentID:5},
    {municipioID:331, nombre:'Espinal', departmentID:73},
    {municipioID:332, nombre:'Facatativá', departmentID:25},
    {municipioID:333, nombre:'Falan', departmentID:73},
    {municipioID:334, nombre:'Filadelfia', departmentID:17},
    {municipioID:335, nombre:'Filandia', departmentID:63},
    {municipioID:336, nombre:'Firavitoba', departmentID:15},
    {municipioID:337, nombre:'Flandes', departmentID:73},
    {municipioID:338, nombre:'Florencia', departmentID:18},
    {municipioID:339, nombre:'Florencia', departmentID:19},
    {municipioID:340, nombre:'Floresta', departmentID:15},
    {municipioID:341, nombre:'Florida', departmentID:76},
    {municipioID:342, nombre:'Floridablanca', departmentID:68},
    {municipioID:343, nombre:'Florián', departmentID:68},
    {municipioID:344, nombre:'Fonseca', departmentID:44},
    {municipioID:345, nombre:'Fortúl', departmentID:81},
    {municipioID:346, nombre:'Fosca', departmentID:25},
    {municipioID:347, nombre:'Francisco Pizarro', departmentID:52},
    {municipioID:348, nombre:'Fredonia', departmentID:5},
    {municipioID:349, nombre:'Fresno', departmentID:73},
    {municipioID:350, nombre:'Frontino', departmentID:5},
    {municipioID:351, nombre:'Fuente de Oro', departmentID:50},
    {municipioID:352, nombre:'Fundación', departmentID:47},
    {municipioID:353, nombre:'Funes', departmentID:52},
    {municipioID:354, nombre:'Funza', departmentID:25},
    {municipioID:355, nombre:'Fusagasugá', departmentID:25},
    {municipioID:356, nombre:'Fómeque', departmentID:25},
    {municipioID:357, nombre:'Fúquene', departmentID:25},
    {municipioID:358, nombre:'Gachalá', departmentID:25},
    {municipioID:359, nombre:'Gachancipá', departmentID:25},
    {municipioID:360, nombre:'Gachantivá', departmentID:15},
    {municipioID:361, nombre:'Gachetá', departmentID:25},
    {municipioID:362, nombre:'Galapa', departmentID:8},
    {municipioID:363, nombre:'Galeras (Nueva Granada)', departmentID:70},
    {municipioID:364, nombre:'Galán', departmentID:68},
    {municipioID:365, nombre:'Gama', departmentID:25},
    {municipioID:366, nombre:'Gamarra', departmentID:20},
    {municipioID:367, nombre:'Garagoa', departmentID:15},
    {municipioID:368, nombre:'Garzón', departmentID:41},
    {municipioID:369, nombre:'Gigante', departmentID:41},
    {municipioID:370, nombre:'Ginebra', departmentID:76},
    {municipioID:371, nombre:'Giraldo', departmentID:5},
    {municipioID:372, nombre:'Girardot', departmentID:25},
    {municipioID:373, nombre:'Girardota', departmentID:5},
    {municipioID:374, nombre:'Girón', departmentID:68},
    {municipioID:375, nombre:'Gonzalez', departmentID:20},
    {municipioID:376, nombre:'Gramalote', departmentID:54},
    {municipioID:377, nombre:'Granada', departmentID:5},
    {municipioID:378, nombre:'Granada', departmentID:25},
    {municipioID:379, nombre:'Granada', departmentID:50},
    {municipioID:380, nombre:'Guaca', departmentID:68},
    {municipioID:381, nombre:'Guacamayas', departmentID:15},
    {municipioID:382, nombre:'Guacarí', departmentID:76},
    {municipioID:383, nombre:'Guachavés', departmentID:52},
    {municipioID:384, nombre:'Guachené', departmentID:19},
    {municipioID:385, nombre:'Guachetá', departmentID:25},
    {municipioID:386, nombre:'Guachucal', departmentID:52},
    {municipioID:387, nombre:'Guadalupe', departmentID:5},
    {municipioID:388, nombre:'Guadalupe', departmentID:41},
    {municipioID:389, nombre:'Guadalupe', departmentID:68},
    {municipioID:390, nombre:'Guaduas', departmentID:25},
    {municipioID:391, nombre:'Guaitarilla', departmentID:52},
    {municipioID:392, nombre:'Gualmatán', departmentID:52},
    {municipioID:393, nombre:'Guamal', departmentID:47},
    {municipioID:394, nombre:'Guamal', departmentID:50},
    {municipioID:395, nombre:'Guamo', departmentID:73},
    {municipioID:396, nombre:'Guapota', departmentID:68},
    {municipioID:397, nombre:'Guapí', departmentID:19},
    {municipioID:398, nombre:'Guaranda', departmentID:70},
    {municipioID:399, nombre:'Guarne', departmentID:5},
    {municipioID:400, nombre:'Guasca', departmentID:25},
    {municipioID:401, nombre:'Guatapé', departmentID:5},
    {municipioID:402, nombre:'Guataquí', departmentID:25},
    {municipioID:403, nombre:'Guatavita', departmentID:25},
    {municipioID:404, nombre:'Guateque', departmentID:15},
    {municipioID:405, nombre:'Guavatá', departmentID:68},
    {municipioID:406, nombre:'Guayabal de Siquima', departmentID:25},
    {municipioID:407, nombre:'Guayabetal', departmentID:25},
    {municipioID:408, nombre:'Guayatá', departmentID:15},
    {municipioID:409, nombre:'Guepsa', departmentID:68},
    {municipioID:410, nombre:'Guicán', departmentID:15},
    {municipioID:411, nombre:'Gutiérrez', departmentID:25},
    {municipioID:412, nombre:'Guática', departmentID:66},
    {municipioID:413, nombre:'Gámbita', departmentID:68},
    {municipioID:414, nombre:'Gámeza', departmentID:15},
    {municipioID:415, nombre:'Génova', departmentID:63},
    {municipioID:416, nombre:'Gómez Plata', departmentID:5},
    {municipioID:417, nombre:'Hacarí', departmentID:54},
    {municipioID:418, nombre:'Hatillo de Loba', departmentID:13},
    {municipioID:419, nombre:'Hato', departmentID:68},
    {municipioID:420, nombre:'Hato Corozal', departmentID:85},
    {municipioID:421, nombre:'Hatonuevo', departmentID:44},
    {municipioID:422, nombre:'Heliconia', departmentID:5},
    {municipioID:423, nombre:'Herrán', departmentID:54},
    {municipioID:424, nombre:'Herveo', departmentID:73},
    {municipioID:425, nombre:'Hispania', departmentID:5},
    {municipioID:426, nombre:'Hobo', departmentID:41},
    {municipioID:427, nombre:'Honda', departmentID:73},
    {municipioID:428, nombre:'Ibagué', departmentID:73},
    {municipioID:429, nombre:'Icononzo', departmentID:73},
    {municipioID:430, nombre:'Iles', departmentID:52},
    {municipioID:431, nombre:'Imúes', departmentID:52},
    {municipioID:432, nombre:'Inzá', departmentID:19},
    {municipioID:433, nombre:'Inírida', departmentID:94},
    {municipioID:434, nombre:'Ipiales', departmentID:52},
    {municipioID:435, nombre:'Isnos', departmentID:41},
    {municipioID:436, nombre:'Istmina', departmentID:27},
    {municipioID:437, nombre:'Itagüí', departmentID:5},
    {municipioID:438, nombre:'Ituango', departmentID:5},
    {municipioID:439, nombre:'Izá', departmentID:15},
    {municipioID:440, nombre:'Jambaló', departmentID:19},
    {municipioID:441, nombre:'Jamundí', departmentID:76},
    {municipioID:442, nombre:'Jardín', departmentID:5},
    {municipioID:443, nombre:'Jenesano', departmentID:15},
    {municipioID:444, nombre:'Jericó', departmentID:5},
    {municipioID:445, nombre:'Jericó', departmentID:15},
    {municipioID:446, nombre:'Jerusalén', departmentID:25},
    {municipioID:447, nombre:'Jesús María', departmentID:68},
    {municipioID:448, nombre:'Jordán', departmentID:68},
    {municipioID:449, nombre:'Juan de Acosta', departmentID:8},
    {municipioID:450, nombre:'Junín', departmentID:25},
    {municipioID:451, nombre:'Juradó', departmentID:27},
    {municipioID:452, nombre:'La Apartada y La Frontera', departmentID:23},
    {municipioID:453, nombre:'La Argentina', departmentID:41},
    {municipioID:454, nombre:'La Belleza', departmentID:68},
    {municipioID:455, nombre:'La Calera', departmentID:25},
    {municipioID:456, nombre:'La Capilla', departmentID:15},
    {municipioID:457, nombre:'La Ceja', departmentID:5},
    {municipioID:458, nombre:'La Celia', departmentID:66},
    {municipioID:459, nombre:'La Cruz', departmentID:52},
    {municipioID:460, nombre:'La Cumbre', departmentID:76},
    {municipioID:461, nombre:'La Dorada', departmentID:17},
    {municipioID:462, nombre:'La Esperanza', departmentID:54},
    {municipioID:463, nombre:'La Estrella', departmentID:5},
    {municipioID:464, nombre:'La Florida', departmentID:52},
    {municipioID:465, nombre:'La Gloria', departmentID:20},
    {municipioID:466, nombre:'La Jagua de Ibirico', departmentID:20},
    {municipioID:467, nombre:'La Jagua del Pilar', departmentID:44},
    {municipioID:468, nombre:'La Llanada', departmentID:52},
    {municipioID:469, nombre:'La Macarena', departmentID:50},
    {municipioID:470, nombre:'La Merced', departmentID:17},
    {municipioID:471, nombre:'La Mesa', departmentID:25},
    {municipioID:472, nombre:'La Montañita', departmentID:18},
    {municipioID:473, nombre:'La Palma', departmentID:25},
    {municipioID:474, nombre:'La Paz', departmentID:68},
    {municipioID:475, nombre:'La Paz (Robles)', departmentID:20},
    {municipioID:476, nombre:'La Peña', departmentID:25},
    {municipioID:477, nombre:'La Pintada', departmentID:5},
    {municipioID:478, nombre:'La Plata', departmentID:41},
    {municipioID:479, nombre:'La Playa', departmentID:54},
    {municipioID:480, nombre:'La Primavera', departmentID:99},
    {municipioID:481, nombre:'La Salina', departmentID:85},
    {municipioID:482, nombre:'La Sierra', departmentID:19},
    {municipioID:483, nombre:'La Tebaida', departmentID:63},
    {municipioID:484, nombre:'La Tola', departmentID:52},
    {municipioID:485, nombre:'La Unión', departmentID:5},
    {municipioID:486, nombre:'La Unión', departmentID:52},
    {municipioID:487, nombre:'La Unión', departmentID:70},
    {municipioID:488, nombre:'La Unión', departmentID:76},
    {municipioID:489, nombre:'La Uvita', departmentID:15},
    {municipioID:490, nombre:'La Vega', departmentID:19},
    {municipioID:491, nombre:'La Vega', departmentID:25},
    {municipioID:492, nombre:'La Victoria', departmentID:15},
    {municipioID:493, nombre:'La Victoria', departmentID:17},
    {municipioID:494, nombre:'La Victoria', departmentID:76},
    {municipioID:495, nombre:'La Virginia', departmentID:66},
    {municipioID:496, nombre:'Labateca', departmentID:54},
    {municipioID:497, nombre:'Labranzagrande', departmentID:15},
    {municipioID:498, nombre:'Landázuri', departmentID:68},
    {municipioID:499, nombre:'Lebrija', departmentID:68},
    {municipioID:500, nombre:'Leiva', departmentID:52},
    {municipioID:501, nombre:'Lejanías', departmentID:50},
    {municipioID:502, nombre:'Lenguazaque', departmentID:25},
    {municipioID:503, nombre:'Leticia', departmentID:91},
    {municipioID:504, nombre:'Liborina', departmentID:5},
    {municipioID:505, nombre:'Linares', departmentID:52},
    {municipioID:506, nombre:'Lloró', departmentID:27},
    {municipioID:507, nombre:'Lorica', departmentID:23},
    {municipioID:508, nombre:'Los Córdobas', departmentID:23},
    {municipioID:509, nombre:'Los Palmitos', departmentID:70},
    {municipioID:510, nombre:'Los Patios', departmentID:54},
    {municipioID:511, nombre:'Los Santos', departmentID:68},
    {municipioID:512, nombre:'Lourdes', departmentID:54},
    {municipioID:513, nombre:'Luruaco', departmentID:8},
    {municipioID:514, nombre:'Lérida', departmentID:73},
    {municipioID:515, nombre:'Líbano', departmentID:73},
    {municipioID:516, nombre:'López (Micay)', departmentID:19},
    {municipioID:517, nombre:'Macanal', departmentID:15},
    {municipioID:518, nombre:'Macaravita', departmentID:68},
    {municipioID:519, nombre:'Maceo', departmentID:5},
    {municipioID:520, nombre:'Machetá', departmentID:25},
    {municipioID:521, nombre:'Madrid', departmentID:25},
    {municipioID:522, nombre:'Magangué', departmentID:13},
    {municipioID:523, nombre:'Magüi (Payán)', departmentID:52},
    {municipioID:524, nombre:'Mahates', departmentID:13},
    {municipioID:525, nombre:'Maicao', departmentID:44},
    {municipioID:526, nombre:'Majagual', departmentID:70},
    {municipioID:527, nombre:'Malambo', departmentID:8},
    {municipioID:528, nombre:'Mallama (Piedrancha)', departmentID:52},
    {municipioID:529, nombre:'Manatí', departmentID:8},
    {municipioID:530, nombre:'Manaure', departmentID:44},
    {municipioID:531, nombre:'Manaure Balcón del Cesar', departmentID:20},
    {municipioID:532, nombre:'Manizales', departmentID:17},
    {municipioID:533, nombre:'Manta', departmentID:25},
    {municipioID:534, nombre:'Manzanares', departmentID:17},
    {municipioID:535, nombre:'Maní', departmentID:85},
    {municipioID:536, nombre:'Mapiripan', departmentID:50},
    {municipioID:537, nombre:'Margarita', departmentID:13},
    {municipioID:538, nombre:'Marinilla', departmentID:5},
    {municipioID:539, nombre:'Maripí', departmentID:15},
    {municipioID:540, nombre:'Mariquita', departmentID:73},
    {municipioID:541, nombre:'Marmato', departmentID:17},
    {municipioID:542, nombre:'Marquetalia', departmentID:17},
    {municipioID:543, nombre:'Marsella', departmentID:66},
    {municipioID:544, nombre:'Marulanda', departmentID:17},
    {municipioID:545, nombre:'María la Baja', departmentID:13},
    {municipioID:546, nombre:'Matanza', departmentID:68},
    {municipioID:547, nombre:'Medellín', departmentID:5},
    {municipioID:548, nombre:'Medina', departmentID:25},
    {municipioID:549, nombre:'Medio Atrato', departmentID:27},
    {municipioID:550, nombre:'Medio Baudó', departmentID:27},
    {municipioID:551, nombre:'Medio San Juan (ANDAGOYA)', departmentID:27},
    {municipioID:552, nombre:'Melgar', departmentID:73},
    {municipioID:553, nombre:'Mercaderes', departmentID:19},
    {municipioID:554, nombre:'Mesetas', departmentID:50},
    {municipioID:555, nombre:'Milán', departmentID:18},
    {municipioID:556, nombre:'Miraflores', departmentID:15},
    {municipioID:557, nombre:'Miraflores', departmentID:95},
    {municipioID:558, nombre:'Miranda', departmentID:19},
    {municipioID:559, nombre:'Mistrató', departmentID:66},
    {municipioID:560, nombre:'Mitú', departmentID:97},
    {municipioID:561, nombre:'Mocoa', departmentID:86},
    {municipioID:562, nombre:'Mogotes', departmentID:68},
    {municipioID:563, nombre:'Molagavita', departmentID:68},
    {municipioID:564, nombre:'Momil', departmentID:23},
    {municipioID:565, nombre:'Mompós', departmentID:13},
    {municipioID:566, nombre:'Mongua', departmentID:15},
    {municipioID:567, nombre:'Monguí', departmentID:15},
    {municipioID:568, nombre:'Moniquirá', departmentID:15},
    {municipioID:569, nombre:'Montebello', departmentID:5},
    {municipioID:570, nombre:'Montecristo', departmentID:13},
    {municipioID:571, nombre:'Montelíbano', departmentID:23},
    {municipioID:572, nombre:'Montenegro', departmentID:63},
    {municipioID:573, nombre:'Monteria', departmentID:23},
    {municipioID:574, nombre:'Monterrey', departmentID:85},
    {municipioID:575, nombre:'Morales', departmentID:13},
    {municipioID:576, nombre:'Morales', departmentID:19},
    {municipioID:577, nombre:'Morelia', departmentID:18},
    {municipioID:578, nombre:'Morroa', departmentID:70},
    {municipioID:579, nombre:'Mosquera', departmentID:25},
    {municipioID:580, nombre:'Mosquera', departmentID:52},
    {municipioID:581, nombre:'Motavita', departmentID:15},
    {municipioID:582, nombre:'Moñitos', departmentID:23},
    {municipioID:583, nombre:'Murillo', departmentID:73},
    {municipioID:584, nombre:'Murindó', departmentID:5},
    {municipioID:585, nombre:'Mutatá', departmentID:5},
    {municipioID:586, nombre:'Mutiscua', departmentID:54},
    {municipioID:587, nombre:'Muzo', departmentID:15},
    {municipioID:588, nombre:'Málaga', departmentID:68},
    {municipioID:589, nombre:'Nariño', departmentID:5},
    {municipioID:590, nombre:'Nariño', departmentID:25},
    {municipioID:591, nombre:'Nariño', departmentID:52},
    {municipioID:592, nombre:'Natagaima', departmentID:73},
    {municipioID:593, nombre:'Nechí', departmentID:5},
    {municipioID:594, nombre:'Necoclí', departmentID:5},
    {municipioID:595, nombre:'Neira', departmentID:17},
    {municipioID:596, nombre:'Neiva', departmentID:41},
    {municipioID:597, nombre:'Nemocón', departmentID:25},
    {municipioID:598, nombre:'Nilo', departmentID:25},
    {municipioID:599, nombre:'Nimaima', departmentID:25},
    {municipioID:600, nombre:'Nobsa', departmentID:15},
    {municipioID:601, nombre:'Nocaima', departmentID:25},
    {municipioID:602, nombre:'Norcasia', departmentID:17},
    {municipioID:603, nombre:'Norosí', departmentID:13},
    {municipioID:604, nombre:'Novita', departmentID:27},
    {municipioID:605, nombre:'Nueva Granada', departmentID:47},
    {municipioID:606, nombre:'Nuevo Colón', departmentID:15},
    {municipioID:607, nombre:'Nunchía', departmentID:85},
    {municipioID:608, nombre:'Nuquí', departmentID:27},
    {municipioID:609, nombre:'Nátaga', departmentID:41},
    {municipioID:610, nombre:'Obando', departmentID:76},
    {municipioID:611, nombre:'Ocamonte', departmentID:68},
    {municipioID:612, nombre:'Ocaña', departmentID:54},
    {municipioID:613, nombre:'Oiba', departmentID:68},
    {municipioID:614, nombre:'Oicatá', departmentID:15},
    {municipioID:615, nombre:'Olaya', departmentID:5},
    {municipioID:616, nombre:'Olaya Herrera', departmentID:52},
    {municipioID:617, nombre:'Onzaga', departmentID:68},
    {municipioID:618, nombre:'Oporapa', departmentID:41},
    {municipioID:619, nombre:'Orito', departmentID:86},
    {municipioID:620, nombre:'Orocué', departmentID:85},
    {municipioID:621, nombre:'Ortega', departmentID:73},
    {municipioID:622, nombre:'Ospina', departmentID:52},
    {municipioID:623, nombre:'Otanche', departmentID:15},
    {municipioID:624, nombre:'Ovejas', departmentID:70},
    {municipioID:625, nombre:'Pachavita', departmentID:15},
    {municipioID:626, nombre:'Pacho', departmentID:25},
    {municipioID:627, nombre:'Padilla', departmentID:19},
    {municipioID:628, nombre:'Paicol', departmentID:41},
    {municipioID:629, nombre:'Pailitas', departmentID:20},
    {municipioID:630, nombre:'Paime', departmentID:25},
    {municipioID:631, nombre:'Paipa', departmentID:15},
    {municipioID:632, nombre:'Pajarito', departmentID:15},
    {municipioID:633, nombre:'Palermo', departmentID:41},
    {municipioID:634, nombre:'Palestina', departmentID:17},
    {municipioID:635, nombre:'Palestina', departmentID:41},
    {municipioID:636, nombre:'Palmar', departmentID:68},
    {municipioID:637, nombre:'Palmar de Varela', departmentID:8},
    {municipioID:638, nombre:'Palmas del Socorro', departmentID:68},
    {municipioID:639, nombre:'Palmira', departmentID:76},
    {municipioID:640, nombre:'Palmito', departmentID:70},
    {municipioID:641, nombre:'Palocabildo', departmentID:73},
    {municipioID:642, nombre:'Pamplona', departmentID:54},
    {municipioID:643, nombre:'Pamplonita', departmentID:54},
    {municipioID:644, nombre:'Pandi', departmentID:25},
    {municipioID:645, nombre:'Panqueba', departmentID:15},
    {municipioID:646, nombre:'Paratebueno', departmentID:25},
    {municipioID:647, nombre:'Pasca', departmentID:25},
    {municipioID:648, nombre:'Patía (El Bordo)', departmentID:19},
    {municipioID:649, nombre:'Pauna', departmentID:15},
    {municipioID:650, nombre:'Paya', departmentID:15},
    {municipioID:651, nombre:'Paz de Ariporo', departmentID:85},
    {municipioID:652, nombre:'Paz de Río', departmentID:15},
    {municipioID:653, nombre:'Pedraza', departmentID:47},
    {municipioID:654, nombre:'Pelaya', departmentID:20},
    {municipioID:655, nombre:'Pensilvania', departmentID:17},
    {municipioID:656, nombre:'Peque', departmentID:5},
    {municipioID:657, nombre:'Pereira', departmentID:66},
    {municipioID:658, nombre:'Pesca', departmentID:15},
    {municipioID:659, nombre:'Peñol', departmentID:5},
    {municipioID:660, nombre:'Piamonte', departmentID:19},
    {municipioID:661, nombre:'Pie de Cuesta', departmentID:68},
    {municipioID:662, nombre:'Piedras', departmentID:73},
    {municipioID:663, nombre:'Piendamó', departmentID:19},
    {municipioID:664, nombre:'Pijao', departmentID:63},
    {municipioID:665, nombre:'Pijiño', departmentID:47},
    {municipioID:666, nombre:'Pinchote', departmentID:68},
    {municipioID:667, nombre:'Pinillos', departmentID:13},
    {municipioID:668, nombre:'Piojo', departmentID:8},
    {municipioID:669, nombre:'Pisva', departmentID:15},
    {municipioID:670, nombre:'Pital', departmentID:41},
    {municipioID:671, nombre:'Pitalito', departmentID:41},
    {municipioID:672, nombre:'Pivijay', departmentID:47},
    {municipioID:673, nombre:'Planadas', departmentID:73},
    {municipioID:674, nombre:'Planeta Rica', departmentID:23},
    {municipioID:675, nombre:'Plato', departmentID:47},
    {municipioID:676, nombre:'Policarpa', departmentID:52},
    {municipioID:677, nombre:'Polonuevo', departmentID:8},
    {municipioID:678, nombre:'Ponedera', departmentID:8},
    {municipioID:679, nombre:'Popayán', departmentID:19},
    {municipioID:680, nombre:'Pore', departmentID:85},
    {municipioID:681, nombre:'Potosí', departmentID:52},
    {municipioID:682, nombre:'Pradera', departmentID:76},
    {municipioID:683, nombre:'Prado', departmentID:73},
    {municipioID:684, nombre:'Providencia', departmentID:52},
    {municipioID:685, nombre:'Providencia', departmentID:88},
    {municipioID:686, nombre:'Pueblo Bello', departmentID:20},
    {municipioID:687, nombre:'Pueblo Nuevo', departmentID:23},
    {municipioID:688, nombre:'Pueblo Rico', departmentID:66},
    {municipioID:689, nombre:'Pueblorrico', departmentID:5},
    {municipioID:690, nombre:'Puebloviejo', departmentID:47},
    {municipioID:691, nombre:'Puente Nacional', departmentID:68},
    {municipioID:692, nombre:'Puerres', departmentID:52},
    {municipioID:693, nombre:'Puerto Asís', departmentID:86},
    {municipioID:694, nombre:'Puerto Berrío', departmentID:5},
    {municipioID:695, nombre:'Puerto Boyacá', departmentID:15},
    {municipioID:696, nombre:'Puerto Caicedo', departmentID:86},
    {municipioID:697, nombre:'Puerto Carreño', departmentID:99},
    {municipioID:698, nombre:'Puerto Colombia', departmentID:8},
    {municipioID:699, nombre:'Puerto Concordia', departmentID:50},
    {municipioID:700, nombre:'Puerto Escondido', departmentID:23},
    {municipioID:701, nombre:'Puerto Gaitán', departmentID:50},
    {municipioID:702, nombre:'Puerto Guzmán', departmentID:86},
    {municipioID:703, nombre:'Puerto Leguízamo', departmentID:86},
    {municipioID:704, nombre:'Puerto Libertador', departmentID:23},
    {municipioID:705, nombre:'Puerto Lleras', departmentID:50},
    {municipioID:706, nombre:'Puerto López', departmentID:50},
    {municipioID:707, nombre:'Puerto Nare', departmentID:5},
    {municipioID:708, nombre:'Puerto Nariño', departmentID:91},
    {municipioID:709, nombre:'Puerto Parra', departmentID:68},
    {municipioID:710, nombre:'Puerto Rico', departmentID:18},
    {municipioID:711, nombre:'Puerto Rico', departmentID:50},
    {municipioID:712, nombre:'Puerto Rondón', departmentID:81},
    {municipioID:713, nombre:'Puerto Salgar', departmentID:25},
    {municipioID:714, nombre:'Puerto Santander', departmentID:54},
    {municipioID:715, nombre:'Puerto Tejada', departmentID:19},
    {municipioID:716, nombre:'Puerto Triunfo', departmentID:5},
    {municipioID:717, nombre:'Puerto Wilches', departmentID:68},
    {municipioID:718, nombre:'Pulí', departmentID:25},
    {municipioID:719, nombre:'Pupiales', departmentID:52},
    {municipioID:720, nombre:'Puracé (Coconuco)', departmentID:19},
    {municipioID:721, nombre:'Purificación', departmentID:73},
    {municipioID:722, nombre:'Purísima', departmentID:23},
    {municipioID:723, nombre:'Pácora', departmentID:17},
    {municipioID:724, nombre:'Páez', departmentID:15},
    {municipioID:725, nombre:'Páez (Belalcazar)', departmentID:19},
    {municipioID:726, nombre:'Páramo', departmentID:68},
    {municipioID:727, nombre:'Quebradanegra', departmentID:25},
    {municipioID:728, nombre:'Quetame', departmentID:25},
    {municipioID:729, nombre:'Quibdó', departmentID:27},
    {municipioID:730, nombre:'Quimbaya', departmentID:63},
    {municipioID:731, nombre:'Quinchía', departmentID:66},
    {municipioID:732, nombre:'Quipama', departmentID:15},
    {municipioID:733, nombre:'Quipile', departmentID:25},
    {municipioID:734, nombre:'Ragonvalia', departmentID:54},
    {municipioID:735, nombre:'Ramiriquí', departmentID:15},
    {municipioID:736, nombre:'Recetor', departmentID:85},
    {municipioID:737, nombre:'Regidor', departmentID:13},
    {municipioID:738, nombre:'Remedios', departmentID:5},
    {municipioID:739, nombre:'Remolino', departmentID:47},
    {municipioID:740, nombre:'Repelón', departmentID:8},
    {municipioID:741, nombre:'Restrepo', departmentID:50},
    {municipioID:742, nombre:'Restrepo', departmentID:76},
    {municipioID:743, nombre:'Retiro', departmentID:5},
    {municipioID:744, nombre:'Ricaurte', departmentID:25},
    {municipioID:745, nombre:'Ricaurte', departmentID:52},
    {municipioID:746, nombre:'Rio Negro', departmentID:68},
    {municipioID:747, nombre:'Rioblanco', departmentID:73},
    {municipioID:748, nombre:'Riofrío', departmentID:76},
    {municipioID:749, nombre:'Riohacha', departmentID:44},
    {municipioID:750, nombre:'Risaralda', departmentID:17},
    {municipioID:751, nombre:'Rivera', departmentID:41},
    {municipioID:752, nombre:'Roberto Payán (San José)', departmentID:52},
    {municipioID:753, nombre:'Roldanillo', departmentID:76},
    {municipioID:754, nombre:'Roncesvalles', departmentID:73},
    {municipioID:755, nombre:'Rondón', departmentID:15},
    {municipioID:756, nombre:'Rosas', departmentID:19},
    {municipioID:757, nombre:'Rovira', departmentID:73},
    {municipioID:758, nombre:'Ráquira', departmentID:15},
    {municipioID:759, nombre:'Río Iró', departmentID:27},
    {municipioID:760, nombre:'Río Quito', departmentID:27},
    {municipioID:761, nombre:'Río Sucio', departmentID:17},
    {municipioID:762, nombre:'Río Viejo', departmentID:13},
    {municipioID:763, nombre:'Río de oro', departmentID:20},
    {municipioID:764, nombre:'Ríonegro', departmentID:5},
    {municipioID:765, nombre:'Ríosucio', departmentID:27},
    {municipioID:766, nombre:'Sabana de Torres', departmentID:68},
    {municipioID:767, nombre:'Sabanagrande', departmentID:8},
    {municipioID:768, nombre:'Sabanalarga', departmentID:5},
    {municipioID:769, nombre:'Sabanalarga', departmentID:8},
    {municipioID:770, nombre:'Sabanalarga', departmentID:85},
    {municipioID:771, nombre:'Sabanas de San Angel (SAN ANGEL)', departmentID:47},
    {municipioID:772, nombre:'Sabaneta', departmentID:5},
    {municipioID:773, nombre:'Saboyá', departmentID:15},
    {municipioID:774, nombre:'Sahagún', departmentID:23},
    {municipioID:775, nombre:'Saladoblanco', departmentID:41},
    {municipioID:776, nombre:'Salamina', departmentID:17},
    {municipioID:777, nombre:'Salamina', departmentID:47},
    {municipioID:778, nombre:'Salazar', departmentID:54},
    {municipioID:779, nombre:'Saldaña', departmentID:73},
    {municipioID:780, nombre:'Salento', departmentID:63},
    {municipioID:781, nombre:'Salgar', departmentID:5},
    {municipioID:782, nombre:'Samacá', departmentID:15},
    {municipioID:783, nombre:'Samaniego', departmentID:52},
    {municipioID:784, nombre:'Samaná', departmentID:17},
    {municipioID:785, nombre:'Sampués', departmentID:70},
    {municipioID:786, nombre:'San Agustín', departmentID:41},
    {municipioID:787, nombre:'San Alberto', departmentID:20},
    {municipioID:788, nombre:'San Andrés', departmentID:68},
    {municipioID:789, nombre:'San Andrés Sotavento', departmentID:23},
    {municipioID:790, nombre:'San Andrés de Cuerquía', departmentID:5},
    {municipioID:791, nombre:'San Antero', departmentID:23},
    {municipioID:792, nombre:'San Antonio', departmentID:73},
    {municipioID:793, nombre:'San Antonio de Tequendama', departmentID:25},
    {municipioID:794, nombre:'San Benito', departmentID:68},
    {municipioID:795, nombre:'San Benito Abad', departmentID:70},
    {municipioID:796, nombre:'San Bernardo', departmentID:25},
    {municipioID:797, nombre:'San Bernardo', departmentID:52},
    {municipioID:798, nombre:'San Bernardo del Viento', departmentID:23},
    {municipioID:799, nombre:'San Calixto', departmentID:54},
    {municipioID:800, nombre:'San Carlos', departmentID:5},
    {municipioID:801, nombre:'San Carlos', departmentID:23},
    {municipioID:802, nombre:'San Carlos de Guaroa', departmentID:50},
    {municipioID:803, nombre:'San Cayetano', departmentID:25},
    {municipioID:804, nombre:'San Cayetano', departmentID:54},
    {municipioID:805, nombre:'San Cristobal', departmentID:13},
    {municipioID:806, nombre:'San Diego', departmentID:20},
    {municipioID:807, nombre:'San Eduardo', departmentID:15},
    {municipioID:808, nombre:'San Estanislao', departmentID:13},
    {municipioID:809, nombre:'San Fernando', departmentID:13},
    {municipioID:810, nombre:'San Francisco', departmentID:5},
    {municipioID:811, nombre:'San Francisco', departmentID:25},
    {municipioID:812, nombre:'San Francisco', departmentID:86},
    {municipioID:813, nombre:'San Gíl', departmentID:68},
    {municipioID:814, nombre:'San Jacinto', departmentID:13},
    {municipioID:815, nombre:'San Jacinto del Cauca', departmentID:13},
    {municipioID:816, nombre:'San Jerónimo', departmentID:5},
    {municipioID:817, nombre:'San Joaquín', departmentID:68},
    {municipioID:818, nombre:'San José', departmentID:17},
    {municipioID:819, nombre:'San José de Miranda', departmentID:68},
    {municipioID:820, nombre:'San José de Montaña', departmentID:5},
    {municipioID:821, nombre:'San José de Pare', departmentID:15},
    {municipioID:822, nombre:'San José de Uré', departmentID:23},
    {municipioID:823, nombre:'San José del Fragua', departmentID:18},
    {municipioID:824, nombre:'San José del Guaviare', departmentID:95},
    {municipioID:825, nombre:'San José del Palmar', departmentID:27},
    {municipioID:826, nombre:'San Juan de Arama', departmentID:50},
    {municipioID:827, nombre:'San Juan de Betulia', departmentID:70},
    {municipioID:828, nombre:'San Juan de Nepomuceno', departmentID:13},
    {municipioID:829, nombre:'San Juan de Pasto', departmentID:52},
    {municipioID:830, nombre:'San Juan de Río Seco', departmentID:25},
    {municipioID:831, nombre:'San Juan de Urabá', departmentID:5},
    {municipioID:832, nombre:'San Juan del Cesar', departmentID:44},
    {municipioID:833, nombre:'San Juanito', departmentID:50},
    {municipioID:834, nombre:'San Lorenzo', departmentID:52},
    {municipioID:835, nombre:'San Luis', departmentID:73},
    {municipioID:836, nombre:'San Luís', departmentID:5},
    {municipioID:837, nombre:'San Luís de Gaceno', departmentID:15},
    {municipioID:838, nombre:'San Luís de Palenque', departmentID:85},
    {municipioID:839, nombre:'San Marcos', departmentID:70},
    {municipioID:840, nombre:'San Martín', departmentID:20},
    {municipioID:841, nombre:'San Martín', departmentID:50},
    {municipioID:842, nombre:'San Martín de Loba', departmentID:13},
    {municipioID:843, nombre:'San Mateo', departmentID:15},
    {municipioID:844, nombre:'San Miguel', departmentID:68},
    {municipioID:845, nombre:'San Miguel', departmentID:86},
    {municipioID:846, nombre:'San Miguel de Sema', departmentID:15},
    {municipioID:847, nombre:'San Onofre', departmentID:70},
    {municipioID:848, nombre:'San Pablo', departmentID:13},
    {municipioID:849, nombre:'San Pablo', departmentID:52},
    {municipioID:850, nombre:'San Pablo de Borbur', departmentID:15},
    {municipioID:851, nombre:'San Pedro', departmentID:5},
    {municipioID:852, nombre:'San Pedro', departmentID:70},
    {municipioID:853, nombre:'San Pedro', departmentID:76},
    {municipioID:854, nombre:'San Pedro de Cartago', departmentID:52},
    {municipioID:855, nombre:'San Pedro de Urabá', departmentID:5},
    {municipioID:856, nombre:'San Pelayo', departmentID:23},
    {municipioID:857, nombre:'San Rafael', departmentID:5},
    {municipioID:858, nombre:'San Roque', departmentID:5},
    {municipioID:859, nombre:'San Sebastián', departmentID:19},
    {municipioID:860, nombre:'San Sebastián de Buenavista', departmentID:47},
    {municipioID:861, nombre:'San Vicente', departmentID:5},
    {municipioID:862, nombre:'San Vicente del Caguán', departmentID:18},
    {municipioID:863, nombre:'San Vicente del Chucurí', departmentID:68},
    {municipioID:864, nombre:'San Zenón', departmentID:47},
    {municipioID:865, nombre:'Sandoná', departmentID:52},
    {municipioID:866, nombre:'Santa Ana', departmentID:47},
    {municipioID:867, nombre:'Santa Bárbara', departmentID:5},
    {municipioID:868, nombre:'Santa Bárbara', departmentID:68},
    {municipioID:869, nombre:'Santa Bárbara (Iscuandé)', departmentID:52},
    {municipioID:870, nombre:'Santa Bárbara de Pinto', departmentID:47},
    {municipioID:871, nombre:'Santa Catalina', departmentID:13},
    {municipioID:872, nombre:'Santa Fé de Antioquia', departmentID:5},
    {municipioID:873, nombre:'Santa Genoveva de Docorodó', departmentID:27},
    {municipioID:874, nombre:'Santa Helena del Opón', departmentID:68},
    {municipioID:875, nombre:'Santa Isabel', departmentID:73},
    {municipioID:876, nombre:'Santa Lucía', departmentID:8},
    {municipioID:877, nombre:'Santa Marta', departmentID:47},
    {municipioID:878, nombre:'Santa María', departmentID:15},
    {municipioID:879, nombre:'Santa María', departmentID:41},
    {municipioID:880, nombre:'Santa Rosa', departmentID:13},
    {municipioID:881, nombre:'Santa Rosa', departmentID:19},
    {municipioID:882, nombre:'Santa Rosa de Cabal', departmentID:66},
    {municipioID:883, nombre:'Santa Rosa de Osos', departmentID:5},
    {municipioID:884, nombre:'Santa Rosa de Viterbo', departmentID:15},
    {municipioID:885, nombre:'Santa Rosa del Sur', departmentID:13},
    {municipioID:886, nombre:'Santa Rosalía', departmentID:99},
    {municipioID:887, nombre:'Santa Sofía', departmentID:15},
    {municipioID:888, nombre:'Santana', departmentID:15},
    {municipioID:889, nombre:'Santander de Quilichao', departmentID:19},
    {municipioID:890, nombre:'Santiago', departmentID:54},
    {municipioID:891, nombre:'Santiago', departmentID:86},
    {municipioID:892, nombre:'Santo Domingo', departmentID:5},
    {municipioID:893, nombre:'Santo Tomás', departmentID:8},
    {municipioID:894, nombre:'Santuario', departmentID:5},
    {municipioID:895, nombre:'Santuario', departmentID:66},
    {municipioID:896, nombre:'Sapuyes', departmentID:52},
    {municipioID:897, nombre:'Saravena', departmentID:81},
    {municipioID:898, nombre:'Sardinata', departmentID:54},
    {municipioID:899, nombre:'Sasaima', departmentID:25},
    {municipioID:900, nombre:'Sativanorte', departmentID:15},
    {municipioID:901, nombre:'Sativasur', departmentID:15},
    {municipioID:902, nombre:'Segovia', departmentID:5},
    {municipioID:903, nombre:'Sesquilé', departmentID:25},
    {municipioID:904, nombre:'Sevilla', departmentID:76},
    {municipioID:905, nombre:'Siachoque', departmentID:15},
    {municipioID:906, nombre:'Sibaté', departmentID:25},
    {municipioID:907, nombre:'Sibundoy', departmentID:86},
    {municipioID:908, nombre:'Silos', departmentID:54},
    {municipioID:909, nombre:'Silvania', departmentID:25},
    {municipioID:910, nombre:'Silvia', departmentID:19},
    {municipioID:911, nombre:'Simacota', departmentID:68},
    {municipioID:912, nombre:'Simijaca', departmentID:25},
    {municipioID:913, nombre:'Simití', departmentID:13},
    {municipioID:914, nombre:'Sincelejo', departmentID:70},
    {municipioID:915, nombre:'Sincé', departmentID:70},
    {municipioID:916, nombre:'Sipí', departmentID:27},
    {municipioID:917, nombre:'Sitionuevo', departmentID:47},
    {municipioID:918, nombre:'Soacha', departmentID:25},
    {municipioID:919, nombre:'Soatá', departmentID:15},
    {municipioID:920, nombre:'Socha', departmentID:15},
    {municipioID:921, nombre:'Socorro', departmentID:68},
    {municipioID:922, nombre:'Socotá', departmentID:15},
    {municipioID:923, nombre:'Sogamoso', departmentID:15},
    {municipioID:924, nombre:'Solano', departmentID:18},
    {municipioID:925, nombre:'Soledad', departmentID:8},
    {municipioID:926, nombre:'Solita', departmentID:18},
    {municipioID:927, nombre:'Somondoco', departmentID:15},
    {municipioID:928, nombre:'Sonsón', departmentID:5},
    {municipioID:929, nombre:'Sopetrán', departmentID:5},
    {municipioID:930, nombre:'Soplaviento', departmentID:13},
    {municipioID:931, nombre:'Sopó', departmentID:25},
    {municipioID:932, nombre:'Sora', departmentID:15},
    {municipioID:933, nombre:'Soracá', departmentID:15},
    {municipioID:934, nombre:'Sotaquirá', departmentID:15},
    {municipioID:935, nombre:'Sotara (Paispamba)', departmentID:19},
    {municipioID:936, nombre:'Sotomayor (Los Andes)', departmentID:52},
    {municipioID:937, nombre:'Suaita', departmentID:68},
    {municipioID:938, nombre:'Suan', departmentID:8},
    {municipioID:939, nombre:'Suaza', departmentID:41},
    {municipioID:940, nombre:'Subachoque', departmentID:25},
    {municipioID:941, nombre:'Sucre', departmentID:19},
    {municipioID:942, nombre:'Sucre', departmentID:68},
    {municipioID:943, nombre:'Sucre', departmentID:70},
    {municipioID:944, nombre:'Suesca', departmentID:25},
    {municipioID:945, nombre:'Supatá', departmentID:25},
    {municipioID:946, nombre:'Supía', departmentID:17},
    {municipioID:947, nombre:'Suratá', departmentID:68},
    {municipioID:948, nombre:'Susa', departmentID:25},
    {municipioID:949, nombre:'Susacón', departmentID:15},
    {municipioID:950, nombre:'Sutamarchán', departmentID:15},
    {municipioID:951, nombre:'Sutatausa', departmentID:25},
    {municipioID:952, nombre:'Sutatenza', departmentID:15},
    {municipioID:953, nombre:'Suárez', departmentID:19},
    {municipioID:954, nombre:'Suárez', departmentID:73},
    {municipioID:955, nombre:'Sácama', departmentID:85},
    {municipioID:956, nombre:'Sáchica', departmentID:15},
    {municipioID:957, nombre:'Tabio', departmentID:25},
    {municipioID:958, nombre:'Tadó', departmentID:27},
    {municipioID:959, nombre:'Talaigua Nuevo', departmentID:13},
    {municipioID:960, nombre:'Tamalameque', departmentID:20},
    {municipioID:961, nombre:'Tame', departmentID:81},
    {municipioID:962, nombre:'Taminango', departmentID:52},
    {municipioID:963, nombre:'Tangua', departmentID:52},
    {municipioID:964, nombre:'Taraira', departmentID:97},
    {municipioID:965, nombre:'Tarazá', departmentID:5},
    {municipioID:966, nombre:'Tarqui', departmentID:41},
    {municipioID:967, nombre:'Tarso', departmentID:5},
    {municipioID:968, nombre:'Tasco', departmentID:15},
    {municipioID:969, nombre:'Tauramena', departmentID:85},
    {municipioID:970, nombre:'Tausa', departmentID:25},
    {municipioID:971, nombre:'Tello', departmentID:41},
    {municipioID:972, nombre:'Tena', departmentID:25},
    {municipioID:973, nombre:'Tenerife', departmentID:47},
    {municipioID:974, nombre:'Tenjo', departmentID:25},
    {municipioID:975, nombre:'Tenza', departmentID:15},
    {municipioID:976, nombre:'Teorama', departmentID:54},
    {municipioID:977, nombre:'Teruel', departmentID:41},
    {municipioID:978, nombre:'Tesalia', departmentID:41},
    {municipioID:979, nombre:'Tibacuy', departmentID:25},
    {municipioID:980, nombre:'Tibaná', departmentID:15},
    {municipioID:981, nombre:'Tibasosa', departmentID:15},
    {municipioID:982, nombre:'Tibirita', departmentID:25},
    {municipioID:983, nombre:'Tibú', departmentID:54},
    {municipioID:984, nombre:'Tierralta', departmentID:23},
    {municipioID:985, nombre:'Timaná', departmentID:41},
    {municipioID:986, nombre:'Timbiquí', departmentID:19},
    {municipioID:987, nombre:'Timbío', departmentID:19},
    {municipioID:988, nombre:'Tinjacá', departmentID:15},
    {municipioID:989, nombre:'Tipacoque', departmentID:15},
    {municipioID:990, nombre:'Tiquisio (Puerto Rico)', departmentID:13},
    {municipioID:991, nombre:'Titiribí', departmentID:5},
    {municipioID:992, nombre:'Toca', departmentID:15},
    {municipioID:993, nombre:'Tocaima', departmentID:25},
    {municipioID:994, nombre:'Tocancipá', departmentID:25},
    {municipioID:995, nombre:'Toguí', departmentID:15},
    {municipioID:996, nombre:'Toledo', departmentID:5},
    {municipioID:997, nombre:'Toledo', departmentID:54},
    {municipioID:998, nombre:'Tolú', departmentID:70},
    {municipioID:999, nombre:'Tolú Viejo', departmentID:70},
    {municipioID:1000, nombre:'Tona', departmentID:68},
    {municipioID:1001, nombre:'Topagá', departmentID:15},
    {municipioID:1002, nombre:'Topaipí', departmentID:25},
    {municipioID:1003, nombre:'Toribío', departmentID:19},
    {municipioID:1004, nombre:'Toro', departmentID:76},
    {municipioID:1005, nombre:'Tota', departmentID:15},
    {municipioID:1006, nombre:'Totoró', departmentID:19},
    {municipioID:1007, nombre:'Trinidad', departmentID:85},
    {municipioID:1008, nombre:'Trujillo', departmentID:76},
    {municipioID:1009, nombre:'Tubará', departmentID:8},
    {municipioID:1010, nombre:'Tuchín', departmentID:23},
    {municipioID:1011, nombre:'Tulúa', departmentID:76},
    {municipioID:1012, nombre:'Tumaco', departmentID:52},
    {municipioID:1013, nombre:'Tunja', departmentID:15},
    {municipioID:1014, nombre:'Tunungua', departmentID:15},
    {municipioID:1015, nombre:'Turbaco', departmentID:13},
    {municipioID:1016, nombre:'Turbaná', departmentID:13},
    {municipioID:1017, nombre:'Turbo', departmentID:5},
    {municipioID:1018, nombre:'Turmequé', departmentID:15},
    {municipioID:1019, nombre:'Tuta', departmentID:15},
    {municipioID:1020, nombre:'Tutasá', departmentID:15},
    {municipioID:1021, nombre:'Támara', departmentID:85},
    {municipioID:1022, nombre:'Támesis', departmentID:5},
    {municipioID:1023, nombre:'Túquerres', departmentID:52},
    {municipioID:1024, nombre:'Ubalá', departmentID:25},
    {municipioID:1025, nombre:'Ubaque', departmentID:25},
    {municipioID:1026, nombre:'Ubaté', departmentID:25},
    {municipioID:1027, nombre:'Ulloa', departmentID:76},
    {municipioID:1028, nombre:'Une', departmentID:25},
    {municipioID:1029, nombre:'Unguía', departmentID:27},
    {municipioID:1030, nombre:'Unión Panamericana (ÁNIMAS)', departmentID:27},
    {municipioID:1031, nombre:'Uramita', departmentID:5},
    {municipioID:1032, nombre:'Uribe', departmentID:50},
    {municipioID:1033, nombre:'Uribia', departmentID:44},
    {municipioID:1034, nombre:'Urrao', departmentID:5},
    {municipioID:1035, nombre:'Urumita', departmentID:44},
    {municipioID:1036, nombre:'Usiacuri', departmentID:8},
    {municipioID:1037, nombre:'Valdivia', departmentID:5},
    {municipioID:1038, nombre:'Valencia', departmentID:23},
    {municipioID:1039, nombre:'Valle de San José', departmentID:68},
    {municipioID:1040, nombre:'Valle de San Juan', departmentID:73},
    {municipioID:1041, nombre:'Valle del Guamuez', departmentID:86},
    {municipioID:1042, nombre:'Valledupar', departmentID:20},
    {municipioID:1043, nombre:'Valparaiso', departmentID:5},
    {municipioID:1044, nombre:'Valparaiso', departmentID:18},
    {municipioID:1045, nombre:'Vegachí', departmentID:5},
    {municipioID:1046, nombre:'Venadillo', departmentID:73},
    {municipioID:1047, nombre:'Venecia', departmentID:5},
    {municipioID:1048, nombre:'Venecia (Ospina Pérez)', departmentID:25},
    {municipioID:1049, nombre:'Ventaquemada', departmentID:15},
    {municipioID:1050, nombre:'Vergara', departmentID:25},
    {municipioID:1051, nombre:'Versalles', departmentID:76},
    {municipioID:1052, nombre:'Vetas', departmentID:68},
    {municipioID:1053, nombre:'Viani', departmentID:25},
    {municipioID:1054, nombre:'Vigía del Fuerte', departmentID:5},
    {municipioID:1055, nombre:'Vijes', departmentID:76},
    {municipioID:1056, nombre:'Villa Caro', departmentID:54},
    {municipioID:1057, nombre:'Villa Rica', departmentID:19},
    {municipioID:1058, nombre:'Villa de Leiva', departmentID:15},
    {municipioID:1059, nombre:'Villa del Rosario', departmentID:54},
    {municipioID:1060, nombre:'Villagarzón', departmentID:86},
    {municipioID:1061, nombre:'Villagómez', departmentID:25},
    {municipioID:1062, nombre:'Villahermosa', departmentID:73},
    {municipioID:1063, nombre:'Villamaría', departmentID:17},
    {municipioID:1064, nombre:'Villanueva', departmentID:13},
    {municipioID:1065, nombre:'Villanueva', departmentID:44},
    {municipioID:1066, nombre:'Villanueva', departmentID:68},
    {municipioID:1067, nombre:'Villanueva', departmentID:85},
    {municipioID:1068, nombre:'Villapinzón', departmentID:25},
    {municipioID:1069, nombre:'Villarrica', departmentID:73},
    {municipioID:1070, nombre:'Villavicencio', departmentID:50},
    {municipioID:1071, nombre:'Villavieja', departmentID:41},
    {municipioID:1072, nombre:'Villeta', departmentID:25},
    {municipioID:1073, nombre:'Viotá', departmentID:25},
    {municipioID:1074, nombre:'Viracachá', departmentID:15},
    {municipioID:1075, nombre:'Vista Hermosa', departmentID:50},
    {municipioID:1076, nombre:'Viterbo', departmentID:17},
    {municipioID:1077, nombre:'Vélez', departmentID:68},
    {municipioID:1078, nombre:'Yacopí', departmentID:25},
    {municipioID:1079, nombre:'Yacuanquer', departmentID:52},
    {municipioID:1080, nombre:'Yaguará', departmentID:41},
    {municipioID:1081, nombre:'Yalí', departmentID:5},
    {municipioID:1082, nombre:'Yarumal', departmentID:5},
    {municipioID:1083, nombre:'Yolombó', departmentID:5},
    {municipioID:1084, nombre:'Yondó (Casabe)', departmentID:5},
    {municipioID:1085, nombre:'Yopal', departmentID:85},
    {municipioID:1086, nombre:'Yotoco', departmentID:76},
    {municipioID:1087, nombre:'Yumbo', departmentID:76},
    {municipioID:1088, nombre:'Zambrano', departmentID:13},
    {municipioID:1089, nombre:'Zapatoca', departmentID:68},
    {municipioID:1090, nombre:'Zapayán (PUNTA DE PIEDRAS)', departmentID:47},
    {municipioID:1091, nombre:'Zaragoza', departmentID:5},
    {municipioID:1092, nombre:'Zarzal', departmentID:76},
    {municipioID:1093, nombre:'Zetaquirá', departmentID:15},
    {municipioID:1094, nombre:'Zipacón', departmentID:25},
    {municipioID:1095, nombre:'Zipaquirá', departmentID:25},
    {municipioID:1096, nombre:'Zona Bananera (PRADO - SEVILLA)', departmentID:47},
    {municipioID:1097, nombre:'Ábrego', departmentID:54},
    {municipioID:1098, nombre:'Íquira', departmentID:41},
    {municipioID:1099, nombre:'Úmbita', departmentID:15},
    {municipioID:1100, nombre:'Útica', departmentID:25}
  ]

  //? Insertar departamentos en la base de datos
  for (const departamento of departamentos) {
    await prisma.departamento.create({
      data: {
        departmentID: departamento.departmentID, // Corregido aquí
        nombre: departamento.nombre,
      },
    });
  }

  //?insertar departamentos en la base de datos
  await prisma.municipio.createMany({
    data: municipios.map((municipio) => ({
      municipioID: municipio.municipioID,
      nombre: municipio.nombre,
      departmentID:municipio.departmentID
    })),
  });


  console.log('seeds creados exitosamente...');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
