# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: LAR API CI (Deploy)

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        #node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        clean: false # Evita limpiar el directorio de trabajo

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        NODEJS_SERVER_PORT: ${{ secrets.NODEJS_SERVER_PORT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Copy environment variables file
      run: |
        cp -r /home/env_variables/.env_lar-api /home/LAR/API/actions-runner/lar-api/lar-api/lar-api/.env

    - name: Stop the API (PM2)
      run: |
        pm2 stop lar-api

    - name: Install dependencies (run npm install)
      run: |
        npm install

    - name: API go live
      run: |
        pm2 restart lar-api
    #- run: npm run dev
    #- run: npm run build --if-present
    #- run: npm test
